create table if not exists dogs (
  id bigint generated by default as identity primary key,
  name text not null,
  registered_name text,
  sex text not null,
  role text not null,
  date_of_birth text,
  color text,
  weight real,
  registration_number text,
  microchip_number text,
  health_testing text,
  acquired_from text,
  acquisition_date text,
  purchase_price_cents integer,
  acquisition_notes text,
  status text not null default 'Active',
  next_heat_date text,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists dog_medical_records (
  id bigint generated by default as identity primary key,
  dog_id bigint not null references dogs(id) on delete cascade,
  record_type text not null,
  title text not null,
  record_date text,
  provider text,
  cost_cents integer not null default 0,
  next_due_date text,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists dog_registrations (
  id bigint generated by default as identity primary key,
  dog_id bigint not null references dogs(id) on delete cascade,
  registry text not null,
  registration_number text not null,
  registered_name text,
  issue_date text,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists dog_documents (
  id bigint generated by default as identity primary key,
  dog_id bigint not null references dogs(id) on delete cascade,
  registration_id bigint references dog_registrations(id) on delete set null,
  document_type text not null,
  registry text,
  registration_number text,
  title text not null,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes integer not null,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists buyers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  city text,
  state text,
  application_status text not null default 'Inquiry',
  preferred_sex text,
  preferred_color text,
  household_notes text,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists litters (
  id bigint generated by default as identity primary key,
  name text not null,
  dam_id bigint references dogs(id) on delete set null,
  sire_id bigint references dogs(id) on delete set null,
  breeding_date text,
  due_date text,
  birth_date text,
  expected_count integer,
  status text not null default 'Planned',
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists puppies (
  id bigint generated by default as identity primary key,
  litter_id bigint not null references litters(id) on delete cascade,
  buyer_id bigint references buyers(id) on delete set null,
  name text not null,
  sex text,
  color text,
  birth_date text,
  birth_weight real,
  current_weight real,
  status text not null default 'Available',
  price_cents integer,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists payment_plans (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references buyers(id) on delete cascade,
  name text not null default 'Puppy payment plan',
  total_amount_cents integer not null,
  payment_amount_cents integer not null,
  term_count integer not null,
  frequency text not null default 'Monthly',
  start_date text,
  next_due_date text,
  on_time_credit_cents integer not null default 0,
  credit_eligible boolean not null default true,
  status text not null default 'Active',
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists payment_plan_puppies (
  payment_plan_id bigint not null references payment_plans(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  primary key (payment_plan_id, puppy_id)
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  dog_id bigint references dogs(id) on delete set null,
  buyer_id bigint references buyers(id) on delete set null,
  litter_id bigint references litters(id) on delete set null,
  puppy_id bigint references puppies(id) on delete set null,
  payment_plan_id bigint references payment_plans(id) on delete set null,
  category text,
  description text not null,
  amount_cents integer not null,
  due_date text,
  paid_date text,
  status text not null default 'Pending',
  method text,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists buyer_documents (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references buyers(id) on delete cascade,
  payment_plan_id bigint references payment_plans(id) on delete set null,
  document_type text not null,
  title text not null,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes integer not null,
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists buyer_document_puppies (
  document_id bigint not null references buyer_documents(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  primary key (document_id, puppy_id)
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text not null,
  event_date text not null,
  event_time text,
  related_type text,
  related_id bigint,
  location text,
  status text not null default 'Scheduled',
  notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists puppy_updates (
  id bigint generated by default as identity primary key,
  puppy_id bigint not null references puppies(id) on delete cascade,
  title text not null,
  body text not null,
  week_number integer,
  weight real,
  published boolean not null default false,
  created_at text not null,
  updated_at text not null
);

create index if not exists dogs_name_idx on dogs(name);
create index if not exists buyers_email_idx on buyers(email);
create index if not exists puppies_litter_idx on puppies(litter_id);
create index if not exists transactions_type_idx on transactions(type);
create index if not exists events_date_idx on events(event_date);

-- WhiteLabel multi-tenant ownership. Run the complete file for new installs.
-- Existing single-kennel installs should create their first kennel before backfilling kennel_id.
create table if not exists kennels (
  id uuid primary key default gen_random_uuid(),
  owner_auth_user_id uuid not null references auth.users(id) on delete restrict,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,46}[a-z0-9])$'),
  plan text not null default 'starter' check (plan in ('starter', 'professional', 'studio')),
  custom_domain text unique,
  domain_status text not null default 'not_requested' check (domain_status in ('not_requested', 'pending', 'verified', 'failed')),
  domain_addon_enabled boolean not null default false,
  primary_color text not null default '#087f8c',
  accent_color text not null default '#c68b24',
  font_family text not null default 'Geist',
  primary_breed text not null default 'Dogs',
  legal_name text,
  location text,
  contact_email text,
  contact_phone text,
  website_url text,
  default_puppy_price_cents integer not null default 0 check (default_puppy_price_cents >= 0),
  default_deposit_cents integer not null default 0 check (default_deposit_cents >= 0),
  custom_policy_notice text not null default 'Have a qualified local attorney review all customer-facing policies and contracts before use.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists kennel_members (
  kennel_id uuid not null references kennels(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('owner', 'admin', 'staff')),
  created_at timestamptz not null default now(),
  primary key (kennel_id, auth_user_id)
);

alter table dogs add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table dog_medical_records add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table dog_registrations add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table dog_documents add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table buyers add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table litters add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table puppies add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table payment_plans add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table payment_plan_puppies add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table transactions add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table buyer_documents add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table buyer_document_puppies add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table events add column if not exists kennel_id uuid references kennels(id) on delete cascade;
alter table puppy_updates add column if not exists kennel_id uuid references kennels(id) on delete cascade;

create index if not exists kennel_members_user_idx on kennel_members(auth_user_id);
create index if not exists dogs_kennel_idx on dogs(kennel_id);
create index if not exists buyers_kennel_idx on buyers(kennel_id);
create index if not exists litters_kennel_idx on litters(kennel_id);
create index if not exists puppies_kennel_idx on puppies(kennel_id);
create index if not exists transactions_kennel_idx on transactions(kennel_id);
create index if not exists events_kennel_idx on events(kennel_id);

alter table kennels enable row level security;
alter table kennel_members enable row level security;

drop policy if exists "members can read their kennel" on kennels;
create policy "members can read their kennel" on kennels for select to authenticated
using (exists (select 1 from kennel_members where kennel_members.kennel_id = kennels.id and kennel_members.auth_user_id = auth.uid()));

drop policy if exists "members can read membership" on kennel_members;
create policy "members can read membership" on kennel_members for select to authenticated
using (auth_user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;
