"use client";

import { FormEvent, useMemo, useState } from "react";
import { CalendarClock, Dna, FlaskConical, HeartPulse, Plus, ShieldAlert, TestTube2 } from "lucide-react";
import { analyzeGeneticCompatibility, calculateCoi, GENETICS_DISCLAIMER } from "../lib/pedigree";
import type { GeneticResult } from "../types/breeding";
import { useBreedingData } from "./use-breeding-data";

const value = (row: Record<string, unknown> | undefined, key: string) => String(row?.[key] ?? "");
const label = (row: Record<string, unknown> | undefined) => value(row, "registered_name") || value(row, "call_name") || value(row, "name") || `Dog #${row?.id ?? ""}`;
const shortDate = (date: unknown) => date ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${String(date).slice(0, 10)}T12:00:00`)) : "Not set";
const formRecord = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget).entries());

export function BreedingProgramWorkspace() {
  const { data, loading, saving, error, act } = useBreedingData();
  const [tab, setTab] = useState<"pairings" | "reproduction" | "genetics">("pairings");
  const [sireId, setSireId] = useState(0);
  const [damId, setDamId] = useState(0);
  const [generations, setGenerations] = useState(5);
  const [selectedBreeding, setSelectedBreeding] = useState(0);
  const [selectedCycle, setSelectedCycle] = useState(0);
  const females = data.dogs.filter((dog) => value(dog, "sex").toLowerCase() === "female");
  const males = data.dogs.filter((dog) => value(dog, "sex").toLowerCase() === "male");
  const coi = useMemo(() => sireId && damId ? calculateCoi(sireId, damId, data.dogs, generations) : null, [data.dogs, sireId, damId, generations]);
  const compatibility = useMemo(() => sireId && damId ? analyzeGeneticCompatibility(sireId, damId, data.dog_genetic_results as GeneticResult[]) : [], [data.dog_genetic_results, sireId, damId]);
  const activeBreeding = data.breeding_records.find((record) => Number(record.id) === selectedBreeding) || data.breeding_records[0];
  const activePregnancy = data.pregnancies.find((item) => Number(item.breeding_record_id) === Number(activeBreeding?.id));

  async function submit(action: string, event: FormEvent<HTMLFormElement>, extra: Record<string, unknown> = {}) {
    event.preventDefault();
    const form = event.currentTarget;
    await act(action, { ...formRecord(event), ...extra });
    if (action !== "pregnancy") form.reset();
  }

  if (loading) return <div className="breeding-workspace-state">Loading breeding program…</div>;

  return <div className="breeding-workspace">
    {error && <div className="inline-error">{error}</div>}
    <section className="breeding-hero panel-wide"><div><small>PROFESSIONAL BREEDING MANAGEMENT</small><h2>Plan from pedigree. Record once. Follow every milestone.</h2><p>Pedigree, genetics, reproductive records, calendar automation, and litter outcomes remain connected to the dogs already in MyDogPortal.</p></div><div className="breeding-summary"><span><b>{data.breeding_records.length}</b><small>Pairings</small></span><span><b>{data.heat_cycles.length}</b><small>Heat cycles</small></span><span><b>{data.pregnancies.filter((row) => value(row, "status") === "Confirmed").length}</b><small>Confirmed</small></span></div></section>
    <nav className="breeding-tabs" aria-label="Breeding program workspaces"><button className={tab === "pairings" ? "active" : ""} onClick={() => setTab("pairings")}><FlaskConical size={16}/> Test mating & breedings</button><button className={tab === "reproduction" ? "active" : ""} onClick={() => setTab("reproduction")}><HeartPulse size={16}/> Reproductive management</button><button className={tab === "genetics" ? "active" : ""} onClick={() => setTab("genetics")}><Dna size={16}/> Genetic testing</button></nav>

    {tab === "pairings" && <div className="breeding-two-column">
      <section className="breeding-panel pairing-planner"><header><div><small>PLANNED / TEST MATING</small><h2>Evaluate a pairing</h2></div><TestTube2 size={23}/></header><form onSubmit={(event) => submit("breeding_record", event, { sire_id: sireId, dam_id: damId, coi_generations: generations })} className="breeding-form">
        <label><span>Dam</span><select value={damId || ""} onChange={(event) => setDamId(Number(event.target.value))} required><option value="">Choose female</option>{females.map((dog) => <option key={dog.id} value={dog.id}>{label(dog)}</option>)}</select></label>
        <label><span>Sire</span><select value={sireId || ""} onChange={(event) => setSireId(Number(event.target.value))} required><option value="">Choose male</option>{males.map((dog) => <option key={dog.id} value={dog.id}>{label(dog)}</option>)}</select></label>
        <label><span>Pairing name</span><input name="name" placeholder="Optional working name" /></label><label><span>Status</span><select name="status" defaultValue="Test Mating"><option>Test Mating</option><option>Planned</option><option>Breeding Scheduled</option><option>Bred</option><option>Cancelled</option></select></label>
        <label><span>Breeding method</span><select name="breeding_method" defaultValue=""><option value="">Not selected</option><option>Natural</option><option>Fresh chilled AI</option><option>Frozen AI</option><option>Other</option></select></label><label><span>Scheduled date/time</span><input name="scheduled_at" type="datetime-local" /></label>
        <label><span>COI generations</span><select value={generations} onChange={(event) => setGenerations(Number(event.target.value))}><option value="3">3 generations</option><option value="5">5 generations</option><option value="8">8 generations</option><option value="10">10 generations</option></select></label><label className="wide"><span>Breeder goals and notes</span><textarea name="notes" rows={3} /></label>
        <button className="primary-action wide" disabled={saving || !sireId || !damId}><FlaskConical size={16}/>{saving ? "Saving…" : "Save pairing"}</button>
      </form>
      <div className="pairing-analysis">
        <div className="coi-card"><span><small>ESTIMATED COI</small><b>{coi ? `${coi.percentage.toFixed(3)}%` : "—"}</b></span><span><small>COMPLETENESS</small><b>{coi ? `${coi.pedigreeCompleteness.toFixed(1)}%` : "—"}</b></span><span><small>COMMON ANCESTORS</small><b>{coi?.commonAncestors.length ?? 0}</b></span></div>
        {coi?.commonAncestors.length ? <div className="ancestor-list compact">{coi.commonAncestors.slice(0, 8).map((ancestor) => <div key={ancestor.dog.id}><span><b>{ancestor.dog.registered_name || ancestor.dog.name}</b><small>{ancestor.independentPathPairs} path pair{ancestor.independentPathPairs === 1 ? "" : "s"}</small></span><strong>{(ancestor.contribution * 100).toFixed(4)}%</strong></div>)}</div> : <p className="analysis-empty">Choose a sire and dam to calculate Wright&apos;s COI from every independent common-ancestor path recorded in the pedigree.</p>}
        <div className="compatibility-list">{compatibility.map((item) => <article className={item.level} key={item.condition}><b>{item.condition}</b><span>Sire: {item.sireResult} · Dam: {item.damResult}</span><p>{item.message}</p></article>)}</div><p className="info-disclaimer"><ShieldAlert size={15}/>{GENETICS_DISCLAIMER}</p>
      </div></section>

      <section className="breeding-panel breeding-records"><header><div><small>PAIRING PIPELINE</small><h2>Saved breedings</h2></div><span>{data.breeding_records.length}</span></header>{data.breeding_records.length ? <div className="record-list">{data.breeding_records.map((record) => { const dam = data.dogs.find((dog) => Number(dog.id) === Number(record.dam_id)); const sire = data.dogs.find((dog) => Number(dog.id) === Number(record.sire_id)); const attempts = data.breeding_attempts.filter((attempt) => Number(attempt.breeding_record_id) === Number(record.id)); const pregnancy = data.pregnancies.find((item) => Number(item.breeding_record_id) === Number(record.id)); return <button key={String(record.id)} className={Number(activeBreeding?.id) === Number(record.id) ? "selected" : ""} onClick={() => setSelectedBreeding(Number(record.id))}><span><em>{value(record, "status")}</em><b>{value(record, "name")}</b><small>{label(dam)} × {label(sire)}</small></span><span><b>{Number(record.estimated_coi || 0).toFixed(3)}%</b><small>{attempts.length} attempt{attempts.length === 1 ? "" : "s"} · {pregnancy ? value(pregnancy, "status") : "No pregnancy record"}</small></span></button>; })}</div> : <div className="breeding-empty"><b>No saved pairings</b><p>Select a dam and sire to run a test mating and preserve the plan.</p></div>}
        {activeBreeding && <div className="record-actions"><form onSubmit={(event) => submit("breeding_attempt", event, { breeding_record_id: activeBreeding.id })}><h3>Record breeding attempt</h3><label><span>Date/time</span><input name="attempted_at" type="datetime-local" required /></label><label><span>Method</span><select name="method" required><option value="">Choose</option><option>Natural</option><option>Fresh chilled AI</option><option>Frozen AI</option><option>Other</option></select></label><label className="wide"><span>Notes</span><input name="notes" /></label><button disabled={saving}><Plus size={15}/> Add attempt</button></form>
          <form key={String(activePregnancy?.id || activeBreeding.id)} onSubmit={(event) => submit("pregnancy", event, { breeding_record_id: activeBreeding.id, id: activePregnancy?.id })}><h3>Pregnancy record</h3><label><span>Status</span><select name="status" defaultValue={value(activePregnancy, "status") || "Pending"}><option>Pending</option><option>Confirmed</option><option>Not Pregnant</option><option>Completed</option><option>Lost</option></select></label><label><span>Confirmation</span><select name="confirmation_method" defaultValue={value(activePregnancy, "confirmation_method")}><option value="">Not recorded</option><option>Ultrasound</option><option>Palpation</option><option>Relaxin test</option><option>Other</option></select></label><label><span>Confirmed at</span><input name="confirmed_at" type="datetime-local" defaultValue={value(activePregnancy, "confirmed_at").slice(0,16)} /></label><label><span>Estimated puppy count</span><input name="estimated_puppy_count" type="number" min="0" defaultValue={value(activePregnancy, "estimated_puppy_count")} /></label><label><span>Ultrasound date/time</span><input name="ultrasound_at" type="datetime-local" defaultValue={value(activePregnancy, "ultrasound_at").slice(0,16)} /></label><label><span>Ultrasound result</span><input name="ultrasound_result" placeholder="Findings / count" defaultValue={value(activePregnancy, "ultrasound_result")} /></label><label><span>X-ray date/time</span><input name="xray_at" type="datetime-local" defaultValue={value(activePregnancy, "xray_at").slice(0,16)} /></label><label><span>X-ray result</span><input name="xray_result" placeholder="Findings / count" defaultValue={value(activePregnancy, "xray_result")} /></label><label><span>Litter</span><select name="litter_id" defaultValue={value(activePregnancy, "litter_id")}><option value="">Not linked</option>{data.litters.map((litter) => <option key={String(litter.id)} value={String(litter.id)}>{value(litter, "name")}</option>)}</select></label><label className="wide"><span>Notes</span><input name="notes" defaultValue={value(activePregnancy, "notes")} /></label><button disabled={saving}>Save pregnancy</button></form></div>}
      </section>
    </div>}

    {tab === "reproduction" && <div className="breeding-two-column">
      <section className="breeding-panel"><header><div><small>HEAT HISTORY</small><h2>Record heat cycle</h2></div><CalendarClock size={22}/></header><form className="breeding-form" onSubmit={(event) => submit("heat_cycle", event)}><label><span>Female</span><select name="dog_id" required><option value="">Choose</option>{females.map((dog) => <option key={dog.id} value={dog.id}>{label(dog)}</option>)}</select></label><label><span>Heat start</span><input name="heat_start" type="date" required /></label><label><span>Heat end</span><input name="heat_end" type="date" /></label><label className="wide"><span>Notes</span><textarea name="notes" rows={3}/></label><button className="primary-action wide" disabled={saving}>Save heat cycle</button></form>
        <div className="timeline-list">{[...data.heat_cycles].sort((a,b) => value(b,"heat_start").localeCompare(value(a,"heat_start"))).map((cycle) => { const dog = data.dogs.find((item) => Number(item.id) === Number(cycle.dog_id)); return <button className={Number(cycle.id) === selectedCycle ? "selected" : ""} key={String(cycle.id)} onClick={() => setSelectedCycle(Number(cycle.id))}><time>{shortDate(cycle.heat_start)}</time><span><b>{label(dog)}</b><small>Next estimated: {shortDate(cycle.estimated_next_heat)} · {cycle.average_interval_days ? `${cycle.average_interval_days} day average` : "First recorded cycle"}</small></span></button>; })}</div>
      </section>
      <section className="breeding-panel"><header><div><small>PROGESTERONE</small><h2>Chronological test series</h2></div><TestTube2 size={22}/></header>{selectedCycle ? <><form className="breeding-form" onSubmit={(event) => submit("progesterone_test", event, { heat_cycle_id: selectedCycle })}><label><span>Tested at</span><input name="tested_at" type="datetime-local" required /></label><label><span>Result</span><input name="result" type="number" min="0" step="0.001" required /></label><label><span>Units</span><select name="units" defaultValue="ng/mL"><option>ng/mL</option><option>nmol/L</option></select></label><label><span>Laboratory</span><input name="laboratory" /></label><label className="wide"><span>Notes</span><input name="notes" /></label><button className="primary-action wide" disabled={saving}>Add result</button></form><div className="lab-series">{data.progesterone_tests.filter((test) => Number(test.heat_cycle_id) === selectedCycle).sort((a,b) => value(a,"tested_at").localeCompare(value(b,"tested_at"))).map((test) => <div key={String(test.id)}><time>{new Date(value(test,"tested_at")).toLocaleString()}</time><b>{String(test.result)} {value(test,"units")}</b><span>{value(test,"laboratory") || "Laboratory not recorded"}</span></div>)}</div></> : <div className="breeding-empty"><b>Select a heat cycle</b><p>Choose a cycle from the left to record and review its progesterone series in chronological order.</p></div>}</section>
      <section className="breeding-panel wide-panel"><header><div><small>PREGNANCY TIMELINE</small><h2>Active reproductive records</h2></div></header><div className="pregnancy-grid">{data.pregnancies.map((pregnancy) => { const dam = data.dogs.find((dog) => Number(dog.id) === Number(pregnancy.dam_id)); const sire = data.dogs.find((dog) => Number(dog.id) === Number(pregnancy.sire_id)); return <article key={String(pregnancy.id)}><em>{value(pregnancy,"status")}</em><h3>{label(dam)} × {label(sire)}</h3><dl><div><dt>Confirmed</dt><dd>{shortDate(pregnancy.confirmed_at)}</dd></div><div><dt>Ultrasound</dt><dd>{shortDate(pregnancy.ultrasound_at)}</dd></div><div><dt>X-ray</dt><dd>{shortDate(pregnancy.xray_at)}</dd></div><div><dt>Estimated window</dt><dd>{shortDate(pregnancy.estimated_due_start)} – {shortDate(pregnancy.estimated_due_end)}</dd></div></dl><p>All calculated dates are estimates and should be reviewed with the attending veterinarian.</p></article>; })}</div></section>
    </div>}

    {tab === "genetics" && <div className="breeding-two-column">
      <section className="breeding-panel"><header><div><small>LABORATORY RECORD</small><h2>Add genetic result</h2></div><Dna size={22}/></header><form className="breeding-form" onSubmit={(event) => submit("genetic_result", event)}><label><span>Dog</span><select name="dog_id" required><option value="">Choose</option>{data.dogs.map((dog) => <option key={dog.id} value={dog.id}>{label(dog)}</option>)}</select></label><label><span>Provider</span><input name="provider" placeholder="Embark, Paw Print Genetics…" required /></label><label><span>Test</span><input name="test_name" required /></label><label><span>Gene or condition</span><input name="gene_or_condition" required /></label><label><span>Result</span><select name="result" required><option>Clear</option><option>Carrier</option><option>At Risk</option><option>Affected</option><option>Indeterminate</option><option>Pending</option></select></label><label><span>Inheritance</span><select name="inheritance_mode"><option value="">Not recorded</option><option>Autosomal recessive</option><option>Autosomal dominant</option><option>X-linked</option><option>Complex / polygenic</option><option>Other</option></select></label><label><span>Result date</span><input name="result_date" type="date" /></label><label><span>Lab/reference number</span><input name="laboratory_reference" /></label><label className="wide"><span>Notes</span><textarea name="notes" rows={3}/></label><button className="primary-action wide" disabled={saving}>Save genetic result</button></form></section>
      <section className="breeding-panel"><header><div><small>GENETIC INVENTORY</small><h2>Recorded results</h2></div><span>{data.dog_genetic_results.length}</span></header><div className="genetics-table">{data.dog_genetic_results.map((result) => { const dog = data.dogs.find((candidate) => Number(candidate.id) === Number(result.dog_id)); return <article key={String(result.id)}><span><b>{value(result,"gene_or_condition")}</b><small>{label(dog)} · {value(result,"provider")} · {value(result,"test_name")}</small></span><em className={`genetic-${value(result,"result").toLowerCase().replaceAll(" ","-")}`}>{value(result,"result")}</em></article>; })}</div><p className="info-disclaimer"><ShieldAlert size={15}/>{GENETICS_DISCLAIMER}</p></section>
    </div>}
  </div>;
}
