"use client";

import { FormEvent, useMemo, useState } from "react";
import { Baby, CheckCircle2, Clock3, HeartPulse, Plus, Scale, ShieldAlert } from "lucide-react";
import { puppyWeightTrend } from "../lib/breeding-calculations";
import { useBreedingData } from "./use-breeding-data";

const value = (row: Record<string, unknown> | undefined, key: string) => String(row?.[key] ?? "");
const label = (row: Record<string, unknown> | undefined) => value(row, "registered_name") || value(row, "call_name") || value(row, "name") || "Unknown";
const localDateTime = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };
const formRecord = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget).entries());

export function WhelpingWorkspace() {
  const { data, loading, saving, error, act } = useBreedingData();
  const activeSessions = data.whelping_sessions.filter((session) => value(session, "status") === "Active");
  const [selectedSessionId, setSelectedSessionId] = useState(0);
  const session = activeSessions.find((candidate) => Number(candidate.id) === selectedSessionId) || activeSessions[0];
  const sessionPuppies = data.puppies.filter((puppy) => Number(puppy.whelping_session_id) === Number(session?.id)).sort((left, right) => Number(left.birth_order) - Number(right.birth_order));
  const [selectedPuppyId, setSelectedPuppyId] = useState(0);
  const selectedPuppy = sessionPuppies.find((puppy) => Number(puppy.id) === selectedPuppyId) || sessionPuppies[0];
  const weightEntries = data.puppy_weight_logs.filter((entry) => Number(entry.puppy_id) === Number(selectedPuppy?.id)).map((entry) => ({ measuredAt: value(entry, "measured_at"), weight: Number(entry.weight), unit: value(entry, "unit") }));
  const trend = useMemo(() => selectedPuppy && Number(selectedPuppy.birth_weight) > 0 ? puppyWeightTrend({ birthWeight: Number(selectedPuppy.birth_weight), birthUnit: value(selectedPuppy, "weight_unit") || "oz", entries: weightEntries }) : null, [selectedPuppy, weightEntries]);

  async function submit(action: string, event: FormEvent<HTMLFormElement>, extra: Record<string, unknown> = {}) {
    event.preventDefault();
    const form = event.currentTarget;
    await act(action, { ...formRecord(event), ...extra });
    form.reset();
  }

  if (loading) return <div className="breeding-workspace-state">Preparing Whelping Mode…</div>;

  if (!session) return <div className="whelping-workspace">
    {error && <div className="inline-error">{error}</div>}
    <section className="whelping-start-card"><span><Baby size={31}/></span><small>MOBILE-FIRST DELIVERY RECORD</small><h2>Start Whelping Mode</h2><p>Choose a recorded pregnancy and litter. Every puppy added here becomes the normal puppy record used everywhere else in MyDogPortal.</p>
      {data.pregnancies.filter((pregnancy) => !["Completed", "Not Pregnant", "Lost"].includes(value(pregnancy, "status"))).length ? <form onSubmit={(event) => submit("start_whelping", event)}><label><span>Pregnancy</span><select name="pregnancy_id" required><option value="">Choose pregnancy</option>{data.pregnancies.filter((pregnancy) => !["Completed", "Not Pregnant", "Lost"].includes(value(pregnancy, "status"))).map((pregnancy) => { const dam = data.dogs.find((dog) => Number(dog.id) === Number(pregnancy.dam_id)); const sire = data.dogs.find((dog) => Number(dog.id) === Number(pregnancy.sire_id)); return <option key={String(pregnancy.id)} value={String(pregnancy.id)}>{label(dam)} × {label(sire)} · {value(pregnancy,"status")}</option>; })}</select></label><label><span>Litter</span><select name="litter_id" required><option value="">Choose litter</option>{data.litters.map((litter) => <option key={String(litter.id)} value={String(litter.id)}>{value(litter,"name")}</option>)}</select></label><label><span>Labor started</span><input name="labor_started_at" type="datetime-local" defaultValue={localDateTime()} required /></label><label><span>Notes</span><textarea name="notes" rows={3}/></label><button className="whelping-primary" disabled={saving}>START WHELPING</button></form> : <div className="breeding-empty"><b>No active pregnancy record</b><p>Create or confirm a pregnancy in Breedings, link its litter, then return here to start Whelping Mode.</p></div>}
    </section>
  </div>;

  const dam = data.dogs.find((dog) => Number(dog.id) === Number(session.dam_id));
  const sire = data.dogs.find((dog) => Number(dog.id) === Number(session.sire_id));
  return <div className="whelping-workspace active">
    {error && <div className="inline-error">{error}</div>}
    <header className="whelping-live-bar"><div><i/><span><small>WHELPING IN PROGRESS</small><b>{label(dam)} × {label(sire)}</b></span></div><div><Clock3 size={17}/><span><small>Labor started</small><b>{new Date(value(session,"labor_started_at")).toLocaleString()}</b></span></div><div><Baby size={17}/><span><small>Puppies recorded</small><b>{sessionPuppies.length}</b></span></div>{activeSessions.length > 1 && <select value={String(session.id)} onChange={(event) => setSelectedSessionId(Number(event.target.value))}>{activeSessions.map((item) => <option key={String(item.id)} value={String(item.id)}>Session #{String(item.id)}</option>)}</select>}</header>

    <div className="whelping-layout">
      <section className="whelping-capture"><header><span>{sessionPuppies.length + 1}</span><div><small>NEXT BIRTH</small><h2>Add puppy</h2></div></header><form onSubmit={(event) => submit("add_whelping_puppy", event, { whelping_session_id: session.id, birth_order: sessionPuppies.length + 1 })}>
        <label className="wide"><span>Name or temporary ID</span><input name="name" placeholder={`Puppy ${sessionPuppies.length + 1}`} /></label><label><span>Birth timestamp</span><input name="birth_at" type="datetime-local" defaultValue={localDateTime()} required /></label><label><span>Sex</span><select name="sex"><option value="">Unknown</option><option>Female</option><option>Male</option></select></label><label><span>Color</span><input name="color" /></label><label><span>Markings</span><input name="markings" /></label><label><span>Coat</span><input name="coat_type" /></label><label><span>Collar / ID color</span><input name="collar_color" /></label><label><span>Birth weight</span><input name="birth_weight" type="number" min="0.01" step="0.01" inputMode="decimal" required /></label><label><span>Unit</span><select name="weight_unit" defaultValue="oz"><option value="g">grams</option><option value="kg">kilograms</option><option value="oz">ounces</option><option value="lb">pounds</option></select></label><label><span>Nursing</span><select name="nursing_status"><option value="Not checked">Not checked</option><option>Nursing</option><option>Assisted</option><option>Not nursing</option></select></label><label><span>Status</span><select name="status" defaultValue="Born"><option>Born</option><option>Monitoring</option><option>Stillborn</option><option>Transferred to veterinary care</option></select></label><label className="check wide"><input name="placenta_observed" type="checkbox"/><span>Placenta observed</span></label><label className="wide"><span>Notes</span><textarea name="notes" rows={3}/></label><button className="whelping-primary wide" disabled={saving}><Plus size={19}/>{saving ? "SAVING…" : "ADD NEXT PUPPY"}</button>
      </form></section>

      <section className="whelping-roster"><header><div><small>LIVE BIRTH ROSTER</small><h2>{sessionPuppies.length} recorded</h2></div></header>{sessionPuppies.length ? <div>{sessionPuppies.map((puppy) => <button key={String(puppy.id)} className={Number(selectedPuppy?.id) === Number(puppy.id) ? "selected" : ""} onClick={() => setSelectedPuppyId(Number(puppy.id))}><span className="birth-number">{String(puppy.birth_order)}</span><span><b>{value(puppy,"name")}</b><small>{[value(puppy,"sex"),value(puppy,"color"),value(puppy,"collar_color")].filter(Boolean).join(" · ")}</small></span><span><b>{String(puppy.birth_weight)} {value(puppy,"weight_unit")}</b><small>{new Date(value(puppy,"birth_at")).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</small></span><em>{value(puppy,"nursing_status")}</em></button>)}</div> : <div className="breeding-empty"><b>Waiting for the first puppy</b><p>Use Add Next Puppy. The birth time is filled automatically and remains editable.</p></div>}</section>
    </div>

    {selectedPuppy && <section className="post-birth-panel"><header><div><small>POST-BIRTH TRACKING</small><h2>{value(selectedPuppy,"name")}</h2></div><span><Scale size={20}/>{trend?.latestGrams ? `${trend.latestGrams.toFixed(1)} g latest` : "Birth weight only"}</span></header><div className="post-birth-grid"><form onSubmit={(event) => submit("puppy_weight", event, { puppy_id: selectedPuppy.id })}><h3><Scale size={17}/> Record weight</h3><label><span>Measured at</span><input name="measured_at" type="datetime-local" defaultValue={localDateTime()} required/></label><label><span>Weight</span><input name="weight" type="number" min="0.01" step="0.01" required/></label><label><span>Unit</span><select name="unit" defaultValue={value(selectedPuppy,"weight_unit") || "oz"}><option value="g">g</option><option value="kg">kg</option><option value="oz">oz</option><option value="lb">lb</option></select></label><label><span>Feeding</span><select name="feeding_status"><option value="">Not recorded</option><option>Nursing</option><option>Assisted</option><option>Bottle-fed</option><option>Tube-fed</option></select></label><label className="wide"><span>Notes</span><input name="notes"/></label><button disabled={saving}>Save weight</button></form>
        <form onSubmit={(event) => submit("puppy_care", event, { puppy_id: selectedPuppy.id })}><h3><HeartPulse size={17}/> Record care</h3><label><span>Type</span><select name="care_type"><option>Veterinary examination</option><option>Deworming</option><option>Vaccination</option><option>Medication</option><option>Feeding</option><option>General care</option></select></label><label><span>Title</span><input name="title" required/></label><label><span>Occurred at</span><input name="occurred_at" type="datetime-local" defaultValue={localDateTime()} required/></label><label><span>Next due</span><input name="next_due_at" type="datetime-local"/></label><label><span>Medication</span><input name="medication"/></label><label><span>Dosage</span><input name="dosage"/></label><label className="check wide"><input name="visible_to_family" type="checkbox" defaultChecked/><span>Show this record in the assigned family&apos;s Puppy Portal</span></label><label className="wide"><span>Notes</span><input name="notes"/></label><button disabled={saving}>Save care record</button></form>
        <div className="weight-trend"><h3>Weight trend</h3><div className="trend-metrics"><span><small>FROM BIRTH</small><b>{trend ? `${trend.changeFromBirthPercent >= 0 ? "+" : ""}${trend.changeFromBirthPercent.toFixed(1)}%` : "—"}</b></span><span><small>LATEST CHANGE</small><b>{trend ? `${trend.latestChangePercent >= 0 ? "+" : ""}${trend.latestChangePercent.toFixed(1)}%` : "—"}</b></span><span><small>WEIGHTS</small><b>{weightEntries.length}</b></span></div>{weightEntries.length > 1 && <div className="mini-trend-bars">{weightEntries.slice(-12).map((entry, index) => <i key={`${entry.measuredAt}-${index}`} style={{ height: `${Math.max(15, Math.min(100, (entry.weight / Math.max(...weightEntries.map((item) => item.weight))) * 100))}%` }} title={`${entry.weight} ${entry.unit}`}/>)}</div>}{trend?.warnings.map((warning) => <p className="weight-warning" key={warning}><ShieldAlert size={15}/>{warning}</p>)}<p className="info-disclaimer"><ShieldAlert size={15}/>{trend?.disclaimer}</p></div></div></section>}

    <footer className="whelping-complete"><div><CheckCircle2 size={24}/><span><b>All puppies recorded?</b><small>Completing closes Whelping Mode but keeps every puppy, weight, and care record available.</small></span></div><button disabled={saving} onClick={() => void act("complete_whelping", { whelping_session_id: session.id })}>Complete whelping</button></footer>
  </div>;
}
