import Link from "next/link";
import { ArrowRight, Check, Dog, ExternalLink, FileSignature, Globe2, HeartPulse, MessageSquareText, MonitorSmartphone, PawPrint, PhoneCall, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import "./marketing.css";
import "./services.css";
import { FOUNDING_BREEDER_LIMIT, foundingPricingStatus } from "../../lib/founding-pricing";

export const dynamic = "force-dynamic";

const features = [
  [Dog, "Breeding operations", "Manage dogs, pedigrees, heat cycles, breedings, litters, whelping, and puppy records."],
  [UsersRound, "Families and placements", "Move applicants through approval, matching, contracts, payments, delivery, and follow-up."],
  [HeartPulse, "Health and care", "Keep vaccinations, medical records, registrations, weights, milestones, and documents organized."],
  [WalletCards, "Business control", "Track deposits, balances, payment plans, expenses, due dates, and every placement."],
  [FileSignature, "Documents and signatures", "Create agreements, retain signed records, and share them through secure Puppy Portals."],
  [MessageSquareText, "Communication center", "Coordinate automated email, family updates, reminders, and optional Business Voice."],
] as const;

const featureModules = [
  [Dog, "BREEDING INTELLIGENCE", "Professional + Studio", "Pedigrees, genetics & planned matings", "Move beyond a dog list. Keep lineage and breeding decisions connected to the dogs they affect.", ["3–5 generation pedigree workspace", "COI / inbreeding calculation", "Common-ancestor identification", "Planned and test matings", "Genetic carrier information", "Pairing context kept with each dog"]],
  [HeartPulse, "REPRODUCTIVE MANAGEMENT", "Professional + Studio", "From heat cycle to due date", "Keep reproductive history and the current breeding timeline in one operational record.", ["Heat-cycle history", "Predicted next heat", "Progesterone tests and results", "Breeding dates and pairing attempts", "Estimated due date", "Pregnancy milestones", "Whelping countdown", "Automatic reminders"]],
  [Dog, "WHELPING MODE", "Professional + Studio", "A working screen for the hours that matter", "Capture each newborn as the litter arrives and continue monitoring growth after delivery.", ["Birth time, sex and color / markings", "Collar color and birth weight", "Placenta and nursing status", "Daily weight tracking", "Weight-loss warnings", "Dewormings and vaccinations", "Medications and care notes"]],
  [HeartPulse, "BREEDING CALENDAR", "Professional + Studio", "Let breeding dates build the timeline", "Turn recorded breeding activity into visible upcoming work instead of calculating every milestone by hand.", ["Breeding and due-date timeline", "Pregnancy and whelping milestones", "Upcoming care work", "Program reminders", "Attention items", "Calendar-driven command center"]],
  [UsersRound, "WAITLIST + PUPPY PICKING", "Professional + Studio", "Make the family list operational", "Manage who is waiting, what they want, where they rank, and what happens when selection begins.", ["Family ranking", "Deposit received status", "Male / female preference", "Color and litter preference", "Picking order", "Puppy assignment", "Pass / skip handling", "Move family to the next litter"]],
  [UsersRound, "APPLICATIONS + PLACEMENT", "All plans", "One family record from application forward", "Keep applicant information useful after approval instead of re-entering the same family over and over.", ["Application review and status", "Buyer / family record", "Litter and puppy matching", "Placement milestones", "Go-home readiness", "Pickup and delivery coordination"]],
  [HeartPulse, "PUPPY HEALTH + GROWTH", "All plans", "A record that grows with the puppy", "Organize the health, growth, care and milestone information breeders and families need later.", ["Weights and growth history", "Vaccinations and dewormings", "Medications and veterinary notes", "Registrations and health documents", "Milestones and care history", "Family-facing health information"]],
  [FileSignature, "DOCUMENTS + E-SIGNATURES", "Professional + Studio", "The complete DogBreederDocs packet, connected to the breeder record", "Professional and Studio include the complete editable DogBreederDocs packet plus connected document generation and signature workflows, reducing retyping and keeping the finished paperwork with the puppy and family.", ["Complete DogBreederDocs editable packet included", "Bill of Sale generation", "Puppy Packet generation", "Deposit and placement agreements", "Payment-plan documents", "Health and go-home paperwork", "E-signature workflow", "Signed copies retained with the family"]],
  [WalletCards, "FINANCIAL CONTROL", "All plans", "Know what was paid, what is due, and why", "MyDogPortal tracks breeder business records; puppy-sale payments remain between the breeder and their families.", ["Deposits and balances", "Payment history", "Payment plans and due dates", "Expenses", "Placement financial history", "Outstanding-balance visibility"]],
  [MessageSquareText, "AUTOMATION + COMMUNICATION", "Professional + Studio", "Follow-up that follows the record", "Automate routine breeder administration while keeping communication tied to the right family, puppy and milestone.", ["Application acknowledgements", "Approval notifications", "Payment reminders", "Milestone-triggered updates", "Family update workflows", "Automated breeder email", "Operational alerts and reminders"]],
  [MonitorSmartphone, "PRIVATE PUPPY PORTAL", "All plans", "Give every family one organized place to return", "Each placed family can receive a private, breeder-branded experience containing only the information intended for them.", ["Overview and My Puppy", "Health & Growth", "Updates", "Documents", "Payments", "Schedule", "Pickup & Delivery", "Messages", "Resources and account access"]],
  [Globe2, "WEBSITE + BRAND SYSTEM", "Studio", "Your public brand connected to your operating system", "Studio carries the breeder experience into a customizable public website and branded business presence.", ["Five distinct breeder website templates", "BreederWeb Designer website service", "Kennel colors, photography and content", "Connected public puppy and litter information", "Standard .com brand launch", "Managed website hosting", "Two branded business emails", "Business Voice + custom IVR", "Private portals under the breeder experience"]],
] as const;

const plans = [
  ["Starter", "$29", "$290", "GET ORGANIZED", "For growing programs that need one secure place to run the essentials.", ["Private breeder workspace", "Included kennel subdomain", "Dogs, litters and puppy records", "Applications and family records", "Family Puppy Portals", "Puppy health and growth records", "Vaccinations, dewormings and care history", "Deposits, balances and payment history", "Family messages and breeder updates", "Core calendar and attention items", "Secure tenant-isolated records"]],
  ["Professional", "$69", "$690", "RUN YOUR BREEDING BUSINESS", "For active breeders who want the complete breeding, document, placement, and automation workflow.", ["Everything in Starter", "3–5 generation pedigrees", "COI / inbreeding and common-ancestor tools", "Planned and test matings", "Genetic carrier information", "Heat-cycle and progesterone tracking", "Breeding attempts, due dates and pregnancy milestones", "Whelping Mode + newborn tracking", "Daily weights and weight-loss warnings", "Automated breeding calendar and reminders", "Operational waitlist + puppy-picking order", "Complete DogBreederDocs editable packet included", "Bill of Sale and Puppy Packet generation", "Deposit, placement and payment-plan documents", "E-signature workflow and retained signed copies", "Automated application, payment and milestone emails", "Advanced placement, go-home and business tools"]],
  ["Studio", "$119", "$1,190", "RUN YOUR BUSINESS + YOUR BRAND", "The complete breeder operating system plus the public website, domain, email, voice, and family experience.", ["Everything in Professional", "Five customizable breeder website starting points", "BreederWeb Designer website service", "Connected public puppy and litter information", "Kennel colors, photography, policies and content", "Brand Launch + first-year standard .com — $149 value", "Breeder Website Personalization — $299 value", "Managed website service + two business emails — $299.40/year value", "Business Voice setup + first-year number — $176.88 value", "Phone System Credits — $240/year value", "Standard .com renewal included while Studio remains active", "Branded website → application → Puppy Portal journey", "Over $1,160 in first-year included service value", "Studio subscription rate locked while continuously active"]],
] as const;

const foundingPrices = {
  Starter: ["$19", "$190"],
  Professional: ["$39", "$390"],
  Studio: ["$69", "$690"],
} as const;

const services = [
  [Globe2, "Dog Breeder Web Website Service", "$24.95/month", "Standalone breeder website service with BreederWeb Designer. No MyDogPortal software subscription is required or included.", ["BreederWeb Designer", "Managed website hosting + SSL", "Two branded business email addresses", "Puppy/litter publishing, forms, and embeds", "Brand controls and version history", "MyDogPortal and DogBreederDocs integration ready", "No MyDogPortal software or breeder-management entitlement included"]],
  [Globe2, "Brand Launch", "$149 one-time", "Register and configure an available standard .com under your breeder brand.", ["Available standard .com first-year registration", "Domain and DNS configuration", "SSL connection", "Managed standard .com renewal: $39/year after year one", "Premium domains priced separately"]],
  [MonitorSmartphone, "Breeder Website Personalization", "$299 one-time", "Turn a supported MyDogPortal website style into your kennel's own polished public presence.", ["Your kennel identity, colors, photography, and content", "Supported page and layout personalization", "Connected MyDogPortal information"]],
  [MonitorSmartphone, "Custom Breeder Website", "From $749", "For breeders who need a website created beyond the supported MyDogPortal template system.", ["Custom layout and page planning", "Brand, photography, content, and program presentation", "Connected MyDogPortal information where supported", "Final scope and price confirmed before work begins"]],
  [PhoneCall, "Business Voice", "$69 setup", "A professionally configured local business voice line with your greeting and breeder information.", ["Local number: $8.99/month or $99/year", "Incoming calls: $0.03/minute", "Outgoing calls: $0.04/minute", "Custom IVR/menu, business hours, voicemail, and routing", "Live examples: Willow Creek (276) 250-9512 · Cedar & Creek (276) 276-2757"]],
] as const;

const workflow = [
  [UsersRound, "01", "Application arrives", "Keep the family, application answers, contact information, and review status together from the beginning."],
  [Dog, "02", "Review & match", "Move an approved family into matching and connect the right puppy without rebuilding the record somewhere else."],
  [FileSignature, "03", "Generate documents", "Use information already in the system to prepare agreements, retain signatures, and keep the signed copy with the family."],
  [WalletCards, "04", "Track the money", "Record deposits, balances, payment plans, due dates, expenses, and the financial history behind each placement."],
  [Globe2, "05", "Coordinate go-home", "Keep pickup, delivery, required forms, payment readiness, and final handoff details visible before release."],
  [HeartPulse, "06", "Continue in Puppy Portal", "Give the family one branded place for updates, documents, health records, messages, milestones, and next steps."],
] as const;

const automationCards = [
  [MessageSquareText, "AUTOMATED COMMUNICATION", "Send the right update at the right moment", "Application acknowledgements, approval notices, payment reminders, puppy milestones, and family updates can follow the workflow instead of living on a handwritten follow-up list.", "Fewer forgotten follow-ups"],
  [FileSignature, "DOCUMENT AUTOMATION", "Stop retyping the same buyer and puppy information", "Professional and Studio include the complete DogBreederDocs packet and can prepare breeder documents from information already entered into the system, including placement paperwork, payment-plan documents, and signed family copies.", "Connected to the family record"],
  [UsersRound, "FAMILY EXPERIENCE", "A Puppy Portal that stays useful after the deposit", "Families can return to one private, branded experience for documents, puppy updates, requests, payment information, health and growth records, and go-home preparation.", "Private family access"],
  [MonitorSmartphone, "PUBLIC WEBSITE", "Let your website and operating system work together", "Studio connects a customizable breeder website to the same program you maintain inside MyDogPortal, so public information does not need to become a second business to manage.", "Your brand, not ours"],
] as const;

const valueStack = [
  [UsersRound, "Applications", "Bring applicant answers and family records into the same workflow that follows them after approval."],
  [Dog, "Breeder records", "Keep dogs, litters, puppies, breeding activity, health, and placement context connected."],
  [FileSignature, "Documents + e-signatures", "Professional and Studio include the complete editable DogBreederDocs packet, populate documents from captured information, and keep signed copies with the family."],
  [WalletCards, "Payment tracking", "Keep deposits, balances, payment plans, due dates, and placement records visible together."],
  [HeartPulse, "Puppy Portal", "Give each family one branded place for their puppy, updates, health information, documents, and next steps."],
  [MessageSquareText, "Automation + email", "Let application acknowledgements, reminders, milestones, and family updates follow the record."],
] as const;

const faqs = [
  ["Do I have to replace my current website?", "No. You can use MyDogPortal as your breeder operating system and keep your current public website, choose a Studio template, or request a custom breeder website."],
  ["Can families see my private breeder records?", "No. Breeder operations stay private. Puppy Portals are family-facing experiences that expose only the information and documents intended for that family."],
  ["Are DogBreederDocs documents included?", "The complete editable DogBreederDocs packet is included with Professional and Studio. Starter can purchase DogBreederDocs documents separately. Professional and Studio also add the connected document-generation, e-signature, and retained-copy workflow inside the breeder operating system."],
  ["What exactly does Studio include?", "Studio includes everything in Professional plus Brand Launch and first-year standard .com registration ($149 value), supported breeder website personalization ($299 value), the managed Dog Breeder Web website service with two branded business emails ($299.40/year value), Business Voice setup plus the first year of the local number ($176.88 value), and $240/year in Phone System Credits. That is $1,164.28 in first-year included service value before counting the MyDogPortal software itself. Standard .com renewal is included while Studio remains active after the first year. Premium domains, metered usage above included credits, and ground-up custom websites are separately scoped."],
  ["Are the phone systems all the same?", "No. Business Voice can have its own greeting, voice, menu choices, voicemail, business hours, and routing. The two live example numbers intentionally use different menus."],
  ["Does MyDogPortal process puppy purchases?", "No. MyDogPortal organizes breeder business records and family workflows. Your puppy sales and payment arrangements remain between your breeding program and your families."],
  ["Can I start before deciding on a website or phone system?", "Yes. Starter and Professional can add Dog Breeder Web, Brand Launch, website personalization, or Business Voice later. Studio includes those launch services from the start."],
  ["How does Founding Breeder pricing work?", "The first 100 eligible kennel accounts can receive the introductory Founding rate. That rate stays locked while the subscription remains continuously active. If the subscription is cancelled or allowed to lapse, the Founding rate is forfeited and any later subscription uses the then-current published price."],
  ["Can I cancel without contacting support?", "Yes. MyDogPortal is designed for easy self-service cancellation from your breeder account. You do not need to call, email, or open a support ticket just to cancel your software subscription."],
] as const;

export default async function MarketingPage() {
  const founding = await foundingPricingStatus().catch(() => ({ limit: FOUNDING_BREEDER_LIMIT, claimed: 0, remaining: FOUNDING_BREEDER_LIMIT, available: true, eligible: true }));
  return <main className="marketing-page">
    <nav className="marketing-nav" aria-label="Main navigation">
      <Link className="marketing-brand" href="/"><span className="marketing-brand-mark"><PawPrint size={23}/></span><b>MyDogPortal</b></Link>
      <div><a href="#platform">Platform</a><a href="#features">Features</a><a href="#workflow">Workflow</a><a href="#automation">Automation</a><a href="#customization">Customization</a><a href="#pricing">Pricing</a><a href="#examples">Templates</a><Link href="/login">Sign in</Link><Link className="marketing-nav-cta" href="/signup">Start free trial</Link></div>
    </nav>
    <section className="marketing-hero">
      <div className="marketing-hero-copy">
        <span className="marketing-kicker"><ShieldCheck size={15}/> Built for professional dog breeders</span>
        <h1>Your breeding program.<br/><em>One connected system.</em></h1>
        <p>Run breeding, families, health, finances, documents, communications, and Puppy Portals from one customizable operating system. Automations carry information forward while your kennel name, colors, website, portal, and family experience stay unmistakably yours.</p>
        <div className="marketing-actions"><Link href="/signup">Start your 14-day free trial <ArrowRight size={17}/></Link><a href="#platform">Explore the platform</a></div>
        <div className="marketing-hero-proof"><span><Check size={13}/>14-day platform trial</span><span><Check size={13}/>Automated breeder workflows</span><span><Check size={13}/>Customizable website + Puppy Portal</span><span><Check size={13}/>Cancel anytime from your account</span></div>
      </div>
      <div className="marketing-product-stage" aria-label="Preview of the real MyDogPortal breeder OS and Puppy Portal">
        <div className="marketing-dog-portrait" aria-hidden="true" />
        <div className="marketing-os-preview">
          <header><div><span className="mini-brand-mark"><PawPrint size={10}/></span><b>Willow Creek Chihuahuas</b><small>⌄</small></div><label><span>⌕</span> Search dogs, families, payments…</label><button>+</button><i>◌</i><span className="mini-avatar">SW</span></header>
          <div className="marketing-os-frame">
            <aside><b>Dashboard</b><span>Dogs</span><span>Litters</span><span>Puppies</span><span>Families</span><span>Applications</span><span>Documents</span><span>Payments</span><span>Calendar</span></aside>
            <section><small>KENNEL COMMAND CENTER</small><h2>Good afternoon, Sarah <span>👋</span></h2><p>Here&apos;s what&apos;s happening with your program today.</p>
              <div className="marketing-os-metrics"><span><b>2</b><small>Litters active</small><em>View litters →</em></span><span><b>7</b><small>Puppies</small><em>View puppies →</em></span><span><b>3</b><small>Applications</small><em>Review now →</em></span><span><b>$4,850</b><small>Outstanding</small><em>View payments →</em></span></div>
              <div className="marketing-os-work"><article><header><b>Attention needed</b><i>5</i></header><p>2 applications waiting review <span>›</span></p><p>Puppy vet checks due this week <span>›</span></p><p>1 contract awaiting signature <span>›</span></p><p>2 payments past due <span>›</span></p></article><article><header><b>Breeding calendar</b><em>View calendar</em></header><p><small>MAY 17</small> Ultrasound — Daisy</p><p><small>MAY 20</small> Vet Check — Litter A</p><p><small>MAY 24</small> Go Home — Litter A</p><p><small>MAY 28</small> Progesterone Test — Bella</p></article></div>
              <div className="marketing-os-litter"><b>Litter A · Daisy &amp; Milo</b><em>ACTIVE</em><span>7 puppies · 3 available</span></div>
            </section>
          </div>
        </div>
        <div className="marketing-family-preview"><header><b>Emma&apos;s Portal</b><span>☰</span></header><section><div className="marketing-puppy-photo"/><div><h3>Maple ♡</h3><p>Long Coat Chihuahua · Female</p><small>Born Apr 10, 2025</small><b>Puppy journey <em>6 of 8 milestones</em></b><i><span/></i></div></section><div className="marketing-family-stats"><span><b>6</b><small>Updates</small></span><span><b>1</b><small>Awaiting signature</small></span></div><footer><b>My Puppy</b><span>Health &amp; Growth</span><span>Documents</span><span>Payments</span><span>Messages</span></footer></div>
      </div>
    </section>
    <section className="marketing-trust"><span><Globe2 size={17}/> Your kennel. Your colors. Your domain.</span><span><ShieldCheck size={17}/> Private tenant-isolated records</span><span><UsersRound size={17}/> Branded family experience</span></section>
    <section className="marketing-section" id="platform"><header><span className="marketing-kicker">THE COMPLETE BREEDER OPERATING SYSTEM</span><h2>Run the program. Serve the families. Protect the records.</h2><p>Replace disconnected spreadsheets, inboxes, folders, and payment notes with one operational source of truth.</p></header><div className="marketing-capabilities">{features.map(([Icon,title,text])=><article key={title}><span><Icon size={20}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="marketing-feature-detail" id="features">
      <header><span className="marketing-kicker">WHAT MYDOGPORTAL ACTUALLY DOES</span><h2>A breeder operating system—not a dressed-up contact list.</h2><p>These are the working modules behind the platform. See exactly what the system can track, generate, automate, and share—and which plans include each level of capability.</p></header>
      <div className="marketing-feature-detail-grid">{featureModules.map(([Icon,kicker,tier,title,text,items])=><article key={title}><header><span><Icon size={21}/></span><div><small>{kicker}</small><em>{tier}</em></div></header><h3>{title}</h3><p>{text}</p><ul>{items.map(item=><li key={item}><Check size={13}/>{item}</li>)}</ul></article>)}</div>
    </section>
    <section className="marketing-workflow" id="workflow">
      <header><span className="marketing-kicker">ONE RECORD. ONE CONTINUOUS WORKFLOW.</span><h2>From first application to go-home—and beyond.</h2><p>MyDogPortal keeps the same family and puppy journey connected instead of forcing you to rebuild it across forms, spreadsheets, email threads, documents, and payment notes.</p></header>
      <div className="marketing-workflow-grid">{workflow.map(([Icon,number,title,text])=><article key={number}><div><span>{number}</span><Icon size={19}/></div><h3>{title}</h3><p>{text}</p></article>)}</div>
      <div className="marketing-workflow-result"><ShieldCheck size={19}/><p><b>The result:</b> when you open a family, puppy, litter, payment, or document, you can see the work around it—not just an isolated row of data.</p></div>
    </section>
    <section className="marketing-section marketing-automation" id="automation">
      <header><span className="marketing-kicker">AUTOMATION THAT FOLLOWS THE BREEDER WORKFLOW</span><h2>Do the work once. Let the record carry it forward.</h2><p>Automation should remove repetitive breeder administration without making the family experience feel robotic.</p></header>
      <div className="marketing-automation-grid">{automationCards.map(([Icon,kicker,title,text,result])=><article key={title}><span><Icon size={22}/></span><small>{kicker}</small><h3>{title}</h3><p>{text}</p><footer><Check size={14}/>{result}</footer></article>)}</div>
    </section>
    <section className="marketing-value" id="value">
      <header><span className="marketing-kicker">THE VALUE OF ONE CONNECTED SYSTEM</span><h2>One system instead of five disconnected tools.</h2><p>The value is not another place to type breeder information. It is keeping the information you already entered useful through the rest of the family and puppy journey.</p></header>
      <div className="marketing-value-grid">{valueStack.map(([Icon,title,text])=><article key={title}><span><Icon size={20}/></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>
      <aside><Globe2 size={20}/><div><b>Keep advertising wherever you already find great families.</b><p>MyDogPortal runs what happens next—your application workflow, breeder records, documents, family experience, and ongoing relationship stay under your kennel brand.</p></div></aside>
    </section>
    <section className="marketing-connected" id="customization">
      <div className="marketing-connected-copy"><span className="marketing-kicker">CUSTOMIZATION THAT LOOKS LIKE YOUR KENNEL</span><h2>Your software should carry your brand—not replace it.</h2><p>Choose from five genuinely different breeder website starting points, then personalize the breed, kennel identity, colors, photography, dogs, litters, policies, application, and public content. Your private Puppy Portal carries the same breeder-branded family experience.</p><ul><li><Check size={15}/>Available puppies and planned litters</li><li><Check size={15}/>Dams, sires, health testing, policies, and applications</li><li><Check size={15}/>Your domain, photography, colors, and kennel identity</li><li><Check size={15}/>A clear path from your website into the private Puppy Portal</li></ul><a href="#examples">Compare live website templates <ArrowRight size={15}/></a></div>
      <div className="marketing-connected-window"><header><span><PawPrint size={16}/></span><div><b>YourKennel.com</b><small>Connected breeder website</small></div><i>STUDIO</i></header><div className="marketing-connected-hero"><small>PLANNED LITTER · FALL 2026</small><h3>Raised with purpose.<br/>Matched with care.</h3><p>Public content stays on-brand while the operational record stays protected.</p></div><div className="marketing-connected-data"><span><b>4</b> parent dogs</span><span><b>2</b> planned litters</span><span><b>1</b> connected application</span></div><footer><span>Website</span><ArrowRight size={14}/><span>Application</span><ArrowRight size={14}/><span>Puppy Portal</span></footer></div>
    </section>
    <section className="marketing-section marketing-pricing" id="pricing"><header><span className="marketing-kicker">{founding.available ? "FOUNDING BREEDER PRICING · FIRST 100 KENNELS" : "DETAILED PLANS · MONTHLY OR ANNUAL"}</span><h2>{founding.available ? "Be one of the first 100. Keep the rate you start with." : "Choose the level of operating system your program needs."}</h2><p>{founding.available ? `Founding Breeder pricing is currently available. ${founding.remaining} of ${founding.limit} Founding spots remain. Start with a 14-day free trial, then keep your introductory rate for as long as the subscription remains continuously active.` : "Starter covers the connected essentials. Professional adds serious breeding-management, the complete DogBreederDocs packet, whelping, e-signature, and automation tools. Studio adds the complete breeder brand: website, domain, email and Business Voice."}</p></header><div className="marketing-plans">{plans.map(([name,price,annual,position,note,items])=><article className={name === "Professional" ? "featured" : ""} key={name}>{name === "Professional" && <em>MOST POPULAR</em>}{founding.available && <strong className="founding-ribbon">FOUNDING BREEDER</strong>}<small className="marketing-plan-position">{position}</small><h3>{name}</h3>{founding.available && <div className="regular-plan-price">Regular {price}/month</div>}<p><b>{founding.available ? foundingPrices[name][0] : price}</b><span>/month{founding.available ? " Founding" : ""}</span></p><div className="marketing-plan-annual"><b>{founding.available ? foundingPrices[name][1] : annual}/year</b><span>{founding.available ? `Regular ${annual}/year` : "Two months free"}</span></div><small>{note}</small><ul>{items.map(item=><li key={item}><Check size={14}/>{item}</li>)}</ul><Link href={"/signup?plan=" + name.toLowerCase()}>Start free trial <ArrowRight size={15}/></Link></article>)}</div><p className="marketing-pricing-note">{founding.available && <><b>Founding Breeder terms:</b> Founding pricing is limited to the first 100 eligible kennel accounts. Your Founding rate remains locked only while that subscription stays continuously active. If you cancel or allow the subscription to lapse, Founding pricing is forfeited and any future subscription will be at the then-current published rate.<br/><br/></>}<b>Easy cancellation, without the runaround.</b> Monthly and annual subscriptions use connected PayPal checkout. Your 14-day $0 platform trial is built into the billing plan, and you can cancel your MyDogPortal subscription from your own account without opening a support ticket.</p></section>
    <section className="marketing-section marketing-services" id="services"><header><span className="marketing-kicker">OPTIONAL SERVICES FOR DOG BREEDERS</span><h2>Choose only the services you need.</h2><p>These are separate à-la-carte services for dog breeders. Each card below shows the standalone service and its actual price.</p></header><div className="marketing-service-grid">{services.map(([Icon,name,price,text,items])=><article key={name}><header><span><Icon size={21}/></span><div><h3>{name}</h3><strong>{price}</strong></div></header><p>{text}</p><ul>{items.map(item=><li key={item}><Check size={13}/>{item}</li>)}</ul><Link href="/signup">Choose this service <ArrowRight size={15}/></Link></article>)}</div><aside><ShieldCheck size={18}/><p><b>Studio package: Over $1,160 in first-year included service value · Prices Locked In.</b> Studio combines Brand Launch and first-year standard .com registration ($149), breeder website personalization ($299), the managed Dog Breeder Web website service with two branded business emails ($299.40/year), Business Voice setup plus the first year of the local number ($176.88), and $240/year in Phone System Credits—a $1,164.28 first-year service value before counting the MyDogPortal software itself. Standard .com renewal is included while Studio remains active after year one; otherwise it is $39/year. Usage above the included phone credits, premium domains, and ground-up custom websites are billed separately.</p></aside></section>
    <section className="marketing-section marketing-examples" id="examples">
      <header><span className="marketing-kicker">FIVE CUSTOMIZABLE BREEDER WEBSITE + OS EXAMPLES</span><h2>See the public website. Then step inside the breeder OS.</h2><p>Every example now includes a clickable, read-only breeder workspace filled with realistic sample dogs, litters, families, breeding milestones, documents, payments, automations, and Puppy Portal activity. Every kennel can start with an included <b>yourkennel.mydogportal.site</b> address. Willow Creek demonstrates the custom <b>.com</b> experience; the other four demonstrate the included MyDogPortal kennel address.</p></header>
      <div className="marketing-example-grid">
        <article><span><MonitorSmartphone size={23}/></span><small>WEBSITE TEMPLATE 01 · CHIHUAHUA · CUSTOM .COM EXAMPLE</small><h3>Willow Creek Chihuahuas</h3><p><b>willowcreekchihuahuas.com</b> demonstrates how a customized breeder website looks on its own .com. Bright, polished boutique presentation for a companion-breed program. Business Voice: <a href="tel:+12762509512"><b>(276) 250-9512</b></a>.</p><div className="marketing-example-actions"><a href="https://willowcreekchihuahuas.com" target="_blank" rel="noreferrer">Visit website <ExternalLink size={15}/></a><Link href="/templates/os-demo/willow-creek">Explore OS demo <ArrowRight size={15}/></Link><Link href="/signup?website_template=willow-creek">Choose style <ArrowRight size={15}/></Link></div></article>
        <article><span><Dog size={23}/></span><small>WEBSITE TEMPLATE 02 · GOLDEN RETRIEVER · INCLUDED ADDRESS</small><h3>{"Cedar & Creek Goldens"}</h3><p><b>cedar-creek.mydogportal.site</b> shows the included kennel-address experience. Warm, editorial and outdoors-inspired, with family connection, health testing, and story-first presentation. Business Voice: <a href="tel:+12762762757"><b>(276) 276-2757</b></a>.</p><div className="marketing-example-actions"><Link href="/templates/cedar-creek">View website <ArrowRight size={15}/></Link><Link href="/templates/os-demo/cedar-creek">Explore OS demo <ArrowRight size={15}/></Link><Link href="/signup?website_template=cedar-creek">Choose style <ArrowRight size={15}/></Link></div></article>
        <article><span><MonitorSmartphone size={23}/></span><small>WEBSITE TEMPLATE 03 · STANDARD POODLE · INCLUDED ADDRESS</small><h3>Northstar Standard Poodles</h3><p><b>northstar.mydogportal.site</b> shows the included kennel-address experience. Luxury minimal editorial design centered on refinement, pedigree context, health transparency, and an elevated brand feel.</p><div className="marketing-example-actions"><Link href="/templates/northstar-poodles">View website <ArrowRight size={15}/></Link><Link href="/templates/os-demo/northstar-poodles">Explore OS demo <ArrowRight size={15}/></Link><Link href="/signup?website_template=northstar-poodles">Choose style <ArrowRight size={15}/></Link></div></article>
        <article><span><Dog size={23}/></span><small>WEBSITE TEMPLATE 04 · AUSTRALIAN SHEPHERD · INCLUDED ADDRESS</small><h3>Bluebird Aussies</h3><p><b>bluebird-aussies.mydogportal.site</b> shows the included kennel-address experience. Bright, colorful modern-ranch styling for active programs that want warmth, personality, puppy development, and family storytelling.</p><div className="marketing-example-actions"><Link href="/templates/bluebird-aussies">View website <ArrowRight size={15}/></Link><Link href="/templates/os-demo/bluebird-aussies">Explore OS demo <ArrowRight size={15}/></Link><Link href="/signup?website_template=bluebird-aussies">Choose style <ArrowRight size={15}/></Link></div></article>
        <article><span><ShieldCheck size={23}/></span><small>WEBSITE TEMPLATE 05 · GERMAN SHEPHERD · INCLUDED ADDRESS</small><h3>Ironwood German Shepherds</h3><p><b>ironwood.mydogportal.site</b> shows the included kennel-address experience. Bold structured performance design for working and sport programs emphasizing health, temperament, training, pedigree, and purpose.</p><div className="marketing-example-actions"><Link href="/templates/ironwood-shepherds">View website <ArrowRight size={15}/></Link><Link href="/templates/os-demo/ironwood-shepherds">Explore OS demo <ArrowRight size={15}/></Link><Link href="/signup?website_template=ironwood-shepherds">Choose style <ArrowRight size={15}/></Link></div></article>
      </div>
    </section>
    <section className="marketing-section marketing-faq" id="faq"><header><span className="marketing-kicker">QUESTIONS BEFORE YOU START</span><h2>Built to fit around a real breeding program.</h2><p>Start with the operating system, then add the public-facing pieces and communication tools that make sense for your kennel.</p></header><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="marketing-final"><span><PawPrint size={25}/></span><div><small>MYDOGPORTAL</small><h2>Give your breeding program the operating system it deserves.</h2></div><Link href="/signup">Create your kennel workspace <ArrowRight size={17}/></Link></section>
    <footer className="marketing-footer"><Link className="marketing-brand" href="/"><span className="marketing-brand-mark"><PawPrint size={20}/></span><b>MyDogPortal</b></Link><p>White-label breeder operations and family portals.</p><div><Link href="/login">Sign in</Link><Link href="/signup">Create account</Link></div></footer>
  </main>;
}
