import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Heart, Mountain, PawPrint, ShieldCheck, Sparkles, Sun, UsersRound } from "lucide-react";
import "../collection.css";

export const metadata: Metadata = {
  title: "Bluebird Australian Shepherds | MyDogPortal Website Template",
  description: "A bright modern ranch-style Australian Shepherd breeder website template available through MyDogPortal.",
};

export default function BluebirdAussiesTemplatePage() {
  return <main className="bb-site">
    <div className="template-demo"><span>MYDOGPORTAL WEBSITE TEMPLATE 04</span><p>Demonstration content only. Your kennel, breed, dogs, photography, colors, policies, and content replace the sample.</p><Link href="/signup?website_template=bluebird-aussies">Choose this style <ArrowRight size={13}/></Link></div>
    <nav className="bb-nav"><a className="bb-brand" href="#home"><span><Sun size={21}/></span><div><b>Bluebird Aussies</b><small>RAISED FOR LIFE OUTSIDE</small></div></a><div><a href="#life">Our Program</a><a href="#litters">Litters</a><a href="#portal">Puppy Portal</a><Link href="/portal/login">Family Sign In</Link><a className="bb-apply" href="#apply">Apply for a puppy</a></div></nav>
    <section className="bb-hero" id="home"><div className="bb-hero-copy"><span className="bb-kicker">AUSTRALIAN SHEPHERDS · FAMILY RAISED</span><h1>Made for<br/><em>good days outside.</em></h1><p>Bright, capable Australian Shepherds raised with room to explore, people to love, and a thoughtful foundation for the homes waiting for them.</p><div className="bb-actions"><a href="#litters">See planned litters <ArrowRight size={14}/></a><a href="#life">Meet our program</a></div></div><div className="bb-photo-stack"><div className="bb-main-photo" role="img" aria-label="Australian Shepherd outdoors"/><div className="bb-photo-note"><small>MEET JUNIPER</small><b>Smart, social, athletic—and happiest wherever the family is.</b></div></div></section>
    <section className="bb-values"><article><span><ShieldCheck size={20}/></span><b>Health first</b><p>Transparent parent testing and organized records.</p></article><article><span><UsersRound size={20}/></span><b>Family raised</b><p>Daily life, handling, routines, and people from the start.</p></article><article><span><Mountain size={20}/></span><b>Adventure ready</b><p>Confidence building through thoughtful early experiences.</p></article><article><span><Heart size={20}/></span><b>Matched with care</b><p>Placement guided by puppy development and family goals.</p></article></section>
    <section className="bb-life" id="life"><header className="bb-head"><div><span className="bb-kicker">LIFE AT BLUEBIRD</span><h2>Puppies raised in the middle of real life.</h2></div><p>This style favors photography, personality, and easy-to-scan program information—a warm fit for family, sporting, herding, and active companion breeds.</p></header><div className="bb-life-grid"><article><small>EVERYDAY DEVELOPMENT</small><h3>Confidence starts here.</h3><p>Sample story content for early socialization, handling, surfaces, sounds, play, recovery, and rest.</p></article><article><Sparkles size={24}/><small>WEEKLY MILESTONES</small><h3>Families stay included.</h3><p>Publish puppy progress through connected updates without maintaining another list.</p></article><article><PawPrint size={24}/><small>THOUGHTFUL MATCHING</small><h3>More than first pick.</h3><p>Share how temperament, lifestyle, and breeder observation guide placement.</p></article></div></section>
    <section className="bb-litters" id="litters"><div><span className="bb-kicker">PLANNED LITTERS</span><h2>Follow the next Bluebird generation.</h2><p>Planned pairings and public puppy availability can be presented from the information you maintain in MyDogPortal, keeping the breeder website and operating record aligned.</p></div><div className="bb-litter-list"><article><span><Heart size={18}/></span><div><small>FALL 2026</small><b>Juniper × Boone</b></div><i>FAMILY LIST OPEN</i></article><article><span><PawPrint size={18}/></span><div><small>WINTER 2026</small><b>Maple × Ranger</b></div><i>PLANNED</i></article></div></section>
    <section className="bb-portal" id="portal"><div><span className="bb-kicker">YOUR PUPPY PORTAL</span><h2>Let the fun continue after the application.</h2><p>Every placed family can have one private, breeder-branded home for puppy updates, health and growth, documents, payments, schedule, transportation, messages, and go-home resources.</p><div className="bb-actions"><Link href="/portal/login">Family portal sign in</Link></div></div><div className="bb-portal-card"><header><b>Bluebird Puppy Portal</b><small>PRIVATE FAMILY ACCESS</small></header><section><small>LATEST PUPPY UPDATE</small><h3>Six weeks & finding her brave</h3><div><span><small>WEIGHT</small><b>7.4 lb</b></span><span><small>NEXT</small><b>Vet exam</b></span><span><small>JOURNEY</small><b>80%</b></span></div></section></div></section>
    <section className="bb-apply-section" id="apply"><div><span className="bb-kicker">LET&apos;S GET TO KNOW EACH OTHER</span><h2>Ready for your next adventure?</h2></div><Link href="/signup?website_template=bluebird-aussies">Choose Bluebird style <ArrowRight size={15}/></Link></section>
    <footer className="bb-footer"><b>Bluebird Aussies</b><span>Sample breeder identity · MyDogPortal Website Template 04</span><span>Powered by MyDogPortal</span></footer>
  </main>;
}
