-- Professional breeding management for MyDogPortal.
-- This migration extends the existing kennel_id model. It intentionally does
-- not read, backfill, or modify unrelated organization-based application data.

alter table public.dogs add column if not exists call_name text;
alter table public.dogs add column if not exists breed text;
alter table public.dogs add column if not exists markings text;
alter table public.dogs add column if not exists coat_type text;
alter table public.dogs add column if not exists breeder_name text;
alter table public.dogs add column if not exists owner_name text;
alter table public.dogs add column if not exists sire_id bigint references public.dogs(id) on delete set null;
alter table public.dogs add column if not exists dam_id bigint references public.dogs(id) on delete set null;
alter table public.dogs add column if not exists photo_urls jsonb not null default '[]'::jsonb;

create index if not exists dogs_sire_idx on public.dogs(sire_id);
create index if not exists dogs_dam_idx on public.dogs(dam_id);

create table if not exists public.dog_genetic_results (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  dog_id bigint not null references public.dogs(id) on delete cascade,
  provider text not null,
  test_name text not null,
  gene_or_condition text not null,
  result text not null check (result in ('Clear', 'Carrier', 'At Risk', 'Affected', 'Indeterminate', 'Pending')),
  inheritance_mode text,
  result_date date,
  laboratory_reference text,
  document_id bigint references public.dog_documents(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dog_genetic_results_kennel_dog_idx on public.dog_genetic_results(kennel_id, dog_id);
create index if not exists dog_genetic_results_condition_idx on public.dog_genetic_results(kennel_id, gene_or_condition);

create table if not exists public.heat_cycles (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  dog_id bigint not null references public.dogs(id) on delete cascade,
  heat_start date not null,
  heat_end date,
  estimated_next_heat date,
  average_interval_days integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (heat_end is null or heat_end >= heat_start),
  check (average_interval_days is null or average_interval_days between 60 and 730)
);

create index if not exists heat_cycles_kennel_dog_start_idx on public.heat_cycles(kennel_id, dog_id, heat_start desc);

create table if not exists public.progesterone_tests (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  heat_cycle_id bigint not null references public.heat_cycles(id) on delete cascade,
  tested_at timestamptz not null,
  result numeric(12, 4) not null check (result >= 0),
  units text not null,
  laboratory text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists progesterone_tests_cycle_idx on public.progesterone_tests(kennel_id, heat_cycle_id, tested_at);

create table if not exists public.breeding_records (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  dam_id bigint not null references public.dogs(id) on delete restrict,
  sire_id bigint not null references public.dogs(id) on delete restrict,
  heat_cycle_id bigint references public.heat_cycles(id) on delete set null,
  litter_id bigint references public.litters(id) on delete set null,
  name text not null,
  status text not null default 'Test Mating' check (status in ('Test Mating', 'Planned', 'Breeding Scheduled', 'Bred', 'Cancelled')),
  breeding_method text,
  scheduled_at timestamptz,
  estimated_coi numeric(10, 6),
  coi_generations integer,
  pedigree_completeness numeric(6, 3),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (dam_id <> sire_id)
);

create index if not exists breeding_records_kennel_status_idx on public.breeding_records(kennel_id, status, scheduled_at);
create index if not exists breeding_records_parents_idx on public.breeding_records(kennel_id, dam_id, sire_id);

create table if not exists public.breeding_attempts (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  breeding_record_id bigint not null references public.breeding_records(id) on delete cascade,
  attempted_at timestamptz not null,
  method text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists breeding_attempts_record_idx on public.breeding_attempts(kennel_id, breeding_record_id, attempted_at);

create table if not exists public.pregnancies (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  breeding_record_id bigint not null references public.breeding_records(id) on delete cascade,
  dam_id bigint not null references public.dogs(id) on delete restrict,
  sire_id bigint not null references public.dogs(id) on delete restrict,
  litter_id bigint references public.litters(id) on delete set null,
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed', 'Not Pregnant', 'Completed', 'Lost')),
  confirmation_method text,
  confirmed_at timestamptz,
  ultrasound_at timestamptz,
  ultrasound_result text,
  xray_at timestamptz,
  xray_result text,
  estimated_puppy_count integer check (estimated_puppy_count is null or estimated_puppy_count >= 0),
  estimated_due_start date,
  estimated_due_end date,
  actual_whelping_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (estimated_due_end is null or estimated_due_start is null or estimated_due_end >= estimated_due_start)
);

create index if not exists pregnancies_kennel_status_idx on public.pregnancies(kennel_id, status, estimated_due_start);
alter table public.pregnancies add column if not exists ultrasound_result text;
alter table public.pregnancies add column if not exists xray_result text;

create table if not exists public.whelping_sessions (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  pregnancy_id bigint references public.pregnancies(id) on delete set null,
  litter_id bigint not null references public.litters(id) on delete restrict,
  dam_id bigint not null references public.dogs(id) on delete restrict,
  sire_id bigint references public.dogs(id) on delete set null,
  labor_started_at timestamptz not null,
  completed_at timestamptz,
  status text not null default 'Active' check (status in ('Active', 'Completed', 'Cancelled')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists whelping_sessions_kennel_status_idx on public.whelping_sessions(kennel_id, status, labor_started_at desc);

alter table public.puppies add column if not exists whelping_session_id bigint references public.whelping_sessions(id) on delete set null;
alter table public.puppies add column if not exists birth_at timestamptz;
alter table public.puppies add column if not exists birth_order integer;
alter table public.puppies add column if not exists markings text;
alter table public.puppies add column if not exists coat_type text;
alter table public.puppies add column if not exists collar_color text;
alter table public.puppies add column if not exists weight_unit text;
alter table public.puppies add column if not exists placenta_observed boolean;
alter table public.puppies add column if not exists nursing_status text;
alter table public.puppies add column if not exists health_status text;

create index if not exists puppies_whelping_session_idx on public.puppies(kennel_id, whelping_session_id, birth_order);

create table if not exists public.puppy_weight_logs (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  puppy_id bigint not null references public.puppies(id) on delete cascade,
  measured_at timestamptz not null,
  weight numeric(12, 4) not null check (weight > 0),
  unit text not null check (unit in ('g', 'kg', 'oz', 'lb')),
  feeding_status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists puppy_weight_logs_puppy_idx on public.puppy_weight_logs(kennel_id, puppy_id, measured_at);

create table if not exists public.puppy_care_records (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  puppy_id bigint not null references public.puppies(id) on delete cascade,
  care_type text not null,
  title text not null,
  occurred_at timestamptz not null,
  next_due_at timestamptz,
  provider text,
  medication text,
  dosage text,
  status text not null default 'Completed',
  visible_to_family boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists puppy_care_records_puppy_idx on public.puppy_care_records(kennel_id, puppy_id, occurred_at desc);
create index if not exists puppy_care_records_due_idx on public.puppy_care_records(kennel_id, next_due_at) where next_due_at is not null;

create table if not exists public.kennel_waitlist_entries (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  buyer_id bigint not null references public.buyers(id) on delete cascade,
  litter_id bigint references public.litters(id) on delete set null,
  application_reference text,
  preferred_sex text,
  preferred_color text,
  preferred_coat text,
  other_preferences text,
  deposit_status text not null default 'Not recorded',
  joined_at date not null default current_date,
  priority_rank integer not null,
  picking_position integer,
  assigned_puppy_id bigint references public.puppies(id) on delete set null,
  status text not null default 'Waiting' check (status in ('Waiting', 'Ready to Pick', 'Puppy Assigned', 'Passed', 'Next Litter', 'On Hold', 'Completed', 'Removed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kennel_id, buyer_id, litter_id),
  check (priority_rank > 0),
  check (picking_position is null or picking_position > 0)
);

create index if not exists kennel_waitlist_entries_queue_idx on public.kennel_waitlist_entries(kennel_id, litter_id, status, picking_position, priority_rank);
create unique index if not exists kennel_waitlist_entries_family_litter_unique
  on public.kennel_waitlist_entries(kennel_id, buyer_id, coalesce(litter_id, 0::bigint));

create table if not exists public.kennel_waitlist_history (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  waitlist_entry_id bigint not null references public.kennel_waitlist_entries(id) on delete cascade,
  action text not null,
  previous_status text,
  new_status text,
  previous_position integer,
  new_position integer,
  puppy_id bigint references public.puppies(id) on delete set null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists kennel_waitlist_history_entry_idx on public.kennel_waitlist_history(kennel_id, waitlist_entry_id, created_at desc);

alter table public.events add column if not exists source_type text;
alter table public.events add column if not exists source_id bigint;
alter table public.events add column if not exists automation_key text;
alter table public.events add column if not exists system_generated boolean not null default false;

create unique index if not exists events_automation_key_unique
  on public.events(kennel_id, automation_key)
  where automation_key is not null;

-- Composite tenant keys prevent a valid member of kennel A from linking a new
-- row to an otherwise valid record owned by kennel B. NOT VALID deliberately
-- leaves pre-existing unowned legacy rows untouched while enforcing new work.
create unique index if not exists dogs_kennel_id_unique on public.dogs(kennel_id, id);
create unique index if not exists dog_registrations_kennel_id_unique on public.dog_registrations(kennel_id, id);
create unique index if not exists dog_documents_kennel_id_unique on public.dog_documents(kennel_id, id);
create unique index if not exists buyers_kennel_id_unique on public.buyers(kennel_id, id);
create unique index if not exists litters_kennel_id_unique on public.litters(kennel_id, id);
create unique index if not exists puppies_kennel_id_unique on public.puppies(kennel_id, id);
create unique index if not exists payment_plans_kennel_id_unique on public.payment_plans(kennel_id, id);
create unique index if not exists buyer_documents_kennel_id_unique on public.buyer_documents(kennel_id, id);
create unique index if not exists dog_genetic_results_kennel_id_unique on public.dog_genetic_results(kennel_id, id);
create unique index if not exists heat_cycles_kennel_id_unique on public.heat_cycles(kennel_id, id);
create unique index if not exists breeding_records_kennel_id_unique on public.breeding_records(kennel_id, id);
create unique index if not exists pregnancies_kennel_id_unique on public.pregnancies(kennel_id, id);
create unique index if not exists whelping_sessions_kennel_id_unique on public.whelping_sessions(kennel_id, id);
create unique index if not exists kennel_waitlist_entries_kennel_id_unique on public.kennel_waitlist_entries(kennel_id, id);

do $$
declare relation record;
begin
  for relation in select * from (values
    ('dogs', 'dogs_sire_same_kennel_fk', 'kennel_id, sire_id', 'dogs', 'kennel_id, id', 'no action'),
    ('dogs', 'dogs_dam_same_kennel_fk', 'kennel_id, dam_id', 'dogs', 'kennel_id, id', 'no action'),
    ('dog_medical_records', 'dog_medical_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'cascade'),
    ('dog_registrations', 'dog_registration_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'cascade'),
    ('dog_documents', 'dog_document_dog_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'cascade'),
    ('dog_documents', 'dog_document_registration_same_kennel_fk', 'kennel_id, registration_id', 'dog_registrations', 'kennel_id, id', 'no action'),
    ('litters', 'litter_dam_same_kennel_fk', 'kennel_id, dam_id', 'dogs', 'kennel_id, id', 'no action'),
    ('litters', 'litter_sire_same_kennel_fk', 'kennel_id, sire_id', 'dogs', 'kennel_id, id', 'no action'),
    ('puppies', 'puppy_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'cascade'),
    ('puppies', 'puppy_buyer_same_kennel_fk', 'kennel_id, buyer_id', 'buyers', 'kennel_id, id', 'no action'),
    ('payment_plans', 'payment_plan_buyer_same_kennel_fk', 'kennel_id, buyer_id', 'buyers', 'kennel_id, id', 'cascade'),
    ('payment_plan_puppies', 'plan_puppy_plan_same_kennel_fk', 'kennel_id, payment_plan_id', 'payment_plans', 'kennel_id, id', 'cascade'),
    ('payment_plan_puppies', 'plan_puppy_puppy_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'cascade'),
    ('transactions', 'transaction_dog_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'no action'),
    ('transactions', 'transaction_buyer_same_kennel_fk', 'kennel_id, buyer_id', 'buyers', 'kennel_id, id', 'no action'),
    ('transactions', 'transaction_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'no action'),
    ('transactions', 'transaction_puppy_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'no action'),
    ('transactions', 'transaction_plan_same_kennel_fk', 'kennel_id, payment_plan_id', 'payment_plans', 'kennel_id, id', 'no action'),
    ('puppy_updates', 'puppy_update_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'cascade'),
    ('buyer_documents', 'buyer_document_buyer_same_kennel_fk', 'kennel_id, buyer_id', 'buyers', 'kennel_id, id', 'cascade'),
    ('buyer_documents', 'buyer_document_plan_same_kennel_fk', 'kennel_id, payment_plan_id', 'payment_plans', 'kennel_id, id', 'no action'),
    ('buyer_document_puppies', 'buyer_document_link_document_same_kennel_fk', 'kennel_id, document_id', 'buyer_documents', 'kennel_id, id', 'cascade'),
    ('buyer_document_puppies', 'buyer_document_link_puppy_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'cascade'),
    ('dog_genetic_results', 'genetic_result_dog_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'cascade'),
    ('dog_genetic_results', 'genetic_result_document_same_kennel_fk', 'kennel_id, document_id', 'dog_documents', 'kennel_id, id', 'no action'),
    ('heat_cycles', 'heat_cycle_dog_same_kennel_fk', 'kennel_id, dog_id', 'dogs', 'kennel_id, id', 'cascade'),
    ('progesterone_tests', 'progesterone_cycle_same_kennel_fk', 'kennel_id, heat_cycle_id', 'heat_cycles', 'kennel_id, id', 'cascade'),
    ('breeding_records', 'breeding_dam_same_kennel_fk', 'kennel_id, dam_id', 'dogs', 'kennel_id, id', 'no action'),
    ('breeding_records', 'breeding_sire_same_kennel_fk', 'kennel_id, sire_id', 'dogs', 'kennel_id, id', 'no action'),
    ('breeding_records', 'breeding_heat_same_kennel_fk', 'kennel_id, heat_cycle_id', 'heat_cycles', 'kennel_id, id', 'no action'),
    ('breeding_records', 'breeding_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'no action'),
    ('breeding_attempts', 'breeding_attempt_record_same_kennel_fk', 'kennel_id, breeding_record_id', 'breeding_records', 'kennel_id, id', 'cascade'),
    ('pregnancies', 'pregnancy_record_same_kennel_fk', 'kennel_id, breeding_record_id', 'breeding_records', 'kennel_id, id', 'cascade'),
    ('pregnancies', 'pregnancy_dam_same_kennel_fk', 'kennel_id, dam_id', 'dogs', 'kennel_id, id', 'no action'),
    ('pregnancies', 'pregnancy_sire_same_kennel_fk', 'kennel_id, sire_id', 'dogs', 'kennel_id, id', 'no action'),
    ('pregnancies', 'pregnancy_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'no action'),
    ('whelping_sessions', 'whelping_pregnancy_same_kennel_fk', 'kennel_id, pregnancy_id', 'pregnancies', 'kennel_id, id', 'no action'),
    ('whelping_sessions', 'whelping_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'no action'),
    ('whelping_sessions', 'whelping_dam_same_kennel_fk', 'kennel_id, dam_id', 'dogs', 'kennel_id, id', 'no action'),
    ('whelping_sessions', 'whelping_sire_same_kennel_fk', 'kennel_id, sire_id', 'dogs', 'kennel_id, id', 'no action'),
    ('puppies', 'puppy_whelping_same_kennel_fk', 'kennel_id, whelping_session_id', 'whelping_sessions', 'kennel_id, id', 'no action'),
    ('puppy_weight_logs', 'puppy_weight_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'cascade'),
    ('puppy_care_records', 'puppy_care_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'cascade'),
    ('kennel_waitlist_entries', 'kennel_waitlist_buyer_same_kennel_fk', 'kennel_id, buyer_id', 'buyers', 'kennel_id, id', 'cascade'),
    ('kennel_waitlist_entries', 'kennel_waitlist_litter_same_kennel_fk', 'kennel_id, litter_id', 'litters', 'kennel_id, id', 'no action'),
    ('kennel_waitlist_entries', 'kennel_waitlist_puppy_same_kennel_fk', 'kennel_id, assigned_puppy_id', 'puppies', 'kennel_id, id', 'no action'),
    ('kennel_waitlist_history', 'kennel_waitlist_history_entry_same_kennel_fk', 'kennel_id, waitlist_entry_id', 'kennel_waitlist_entries', 'kennel_id, id', 'cascade'),
    ('kennel_waitlist_history', 'kennel_waitlist_history_puppy_same_kennel_fk', 'kennel_id, puppy_id', 'puppies', 'kennel_id, id', 'no action')
  ) as links(child_table, constraint_name, child_columns, parent_table, parent_columns, delete_action)
  loop
    if not exists (select 1 from pg_constraint where conname = relation.constraint_name) then
      execute format(
        'alter table public.%I add constraint %I foreign key (%s) references public.%I (%s) on delete %s not valid',
        relation.child_table, relation.constraint_name, relation.child_columns,
        relation.parent_table, relation.parent_columns, relation.delete_action
      );
    end if;
  end loop;
end;
$$;

create or replace function public.is_kennel_member(target_kennel_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.kennel_members
    where kennel_id = target_kennel_id and auth_user_id = auth.uid()
  );
$$;

create or replace function public.is_kennel_admin(target_kennel_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.kennel_members
    where kennel_id = target_kennel_id
      and auth_user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$;

create or replace function public.portal_kennel_id()
returns uuid
language plpgsql
stable
as $$
declare candidate text;
begin
  candidate := auth.jwt() -> 'app_metadata' ->> 'portal_kennel_id';
  if candidate is null or candidate !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return null;
  end if;
  return candidate::uuid;
end;
$$;

create or replace function public.portal_buyer_id()
returns bigint
language plpgsql
stable
as $$
declare candidate text;
begin
  candidate := auth.jwt() -> 'app_metadata' ->> 'portal_buyer_id';
  if candidate is null or candidate !~ '^[1-9][0-9]*$' then
    return null;
  end if;
  return candidate::bigint;
end;
$$;

revoke all on function public.is_kennel_member(uuid) from public;
revoke all on function public.is_kennel_admin(uuid) from public;
grant execute on function public.is_kennel_member(uuid) to authenticated;
grant execute on function public.is_kennel_admin(uuid) to authenticated;
grant execute on function public.portal_kennel_id() to authenticated;
grant execute on function public.portal_buyer_id() to authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'dogs', 'dog_medical_records', 'dog_registrations', 'dog_documents',
    'litters', 'buyers', 'puppies', 'payment_plans', 'payment_plan_puppies',
    'transactions', 'events', 'puppy_updates', 'buyer_documents',
    'buyer_document_puppies', 'dog_genetic_results', 'heat_cycles',
    'progesterone_tests', 'breeding_records', 'breeding_attempts', 'pregnancies',
    'whelping_sessions', 'puppy_weight_logs', 'puppy_care_records',
    'kennel_waitlist_entries', 'kennel_waitlist_history'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    execute format('drop policy if exists mydogportal_member_select on public.%I', table_name);
    execute format('drop policy if exists mydogportal_member_insert on public.%I', table_name);
    execute format('drop policy if exists mydogportal_member_update on public.%I', table_name);
    execute format('drop policy if exists mydogportal_member_delete on public.%I', table_name);
    execute format('create policy mydogportal_member_select on public.%I for select to authenticated using (public.is_kennel_member(kennel_id))', table_name);
    execute format('create policy mydogportal_member_insert on public.%I for insert to authenticated with check (public.is_kennel_member(kennel_id))', table_name);
    execute format('create policy mydogportal_member_update on public.%I for update to authenticated using (public.is_kennel_member(kennel_id)) with check (public.is_kennel_member(kennel_id))', table_name);
    execute format('create policy mydogportal_member_delete on public.%I for delete to authenticated using (public.is_kennel_member(kennel_id))', table_name);
  end loop;
end;
$$;

grant select, update on table public.kennels to authenticated;
grant select, insert, update, delete on table public.kennel_members to authenticated;

do $$
declare sequence_name text;
begin
  foreach sequence_name in array array[
    'dog_genetic_results_id_seq', 'heat_cycles_id_seq',
    'progesterone_tests_id_seq', 'breeding_records_id_seq',
    'breeding_attempts_id_seq', 'pregnancies_id_seq',
    'whelping_sessions_id_seq', 'puppy_weight_logs_id_seq',
    'puppy_care_records_id_seq', 'kennel_waitlist_entries_id_seq',
    'kennel_waitlist_history_id_seq'
  ]
  loop
    if to_regclass('public.' || sequence_name) is not null then
      execute format('grant usage, select on sequence public.%I to authenticated', sequence_name);
    end if;
  end loop;
end;
$$;

drop policy if exists mydogportal_kennel_select on public.kennels;
create policy mydogportal_kennel_select on public.kennels for select to authenticated
using (public.is_kennel_member(id));

drop policy if exists mydogportal_kennel_update on public.kennels;
create policy mydogportal_kennel_update on public.kennels for update to authenticated
using (public.is_kennel_admin(id)) with check (public.is_kennel_admin(id));

drop policy if exists mydogportal_membership_select on public.kennel_members;
create policy mydogportal_membership_select on public.kennel_members for select to authenticated
using (auth_user_id = auth.uid() or public.is_kennel_admin(kennel_id));

drop policy if exists mydogportal_membership_manage on public.kennel_members;
create policy mydogportal_membership_manage on public.kennel_members for all to authenticated
using (public.is_kennel_admin(kennel_id)) with check (public.is_kennel_admin(kennel_id));

-- Direct Supabase access for Puppy Portal accounts remains read-only and is
-- constrained by immutable app_metadata claims written by the server.
drop policy if exists mydogportal_portal_buyer_select on public.buyers;
create policy mydogportal_portal_buyer_select on public.buyers for select to authenticated
using (kennel_id = public.portal_kennel_id() and id = public.portal_buyer_id());

drop policy if exists mydogportal_portal_puppy_select on public.puppies;
create policy mydogportal_portal_puppy_select on public.puppies for select to authenticated
using (kennel_id = public.portal_kennel_id() and buyer_id = public.portal_buyer_id());

drop policy if exists mydogportal_portal_update_select on public.puppy_updates;
create policy mydogportal_portal_update_select on public.puppy_updates for select to authenticated
using (
  kennel_id = public.portal_kennel_id() and published = true and exists (
    select 1 from public.puppies
    where puppies.id = puppy_updates.puppy_id
      and puppies.kennel_id = public.portal_kennel_id()
      and puppies.buyer_id = public.portal_buyer_id()
  )
);

drop policy if exists mydogportal_portal_weight_select on public.puppy_weight_logs;
create policy mydogportal_portal_weight_select on public.puppy_weight_logs for select to authenticated
using (
  kennel_id = public.portal_kennel_id() and exists (
    select 1 from public.puppies
    where puppies.id = puppy_weight_logs.puppy_id
      and puppies.kennel_id = public.portal_kennel_id()
      and puppies.buyer_id = public.portal_buyer_id()
  )
);

drop policy if exists mydogportal_portal_care_select on public.puppy_care_records;
create policy mydogportal_portal_care_select on public.puppy_care_records for select to authenticated
using (
  kennel_id = public.portal_kennel_id() and visible_to_family = true and exists (
    select 1 from public.puppies
    where puppies.id = puppy_care_records.puppy_id
      and puppies.kennel_id = public.portal_kennel_id()
      and puppies.buyer_id = public.portal_buyer_id()
  )
);

drop policy if exists mydogportal_portal_transaction_select on public.transactions;
create policy mydogportal_portal_transaction_select on public.transactions for select to authenticated
using (kennel_id = public.portal_kennel_id() and buyer_id = public.portal_buyer_id());

drop policy if exists mydogportal_portal_plan_select on public.payment_plans;
create policy mydogportal_portal_plan_select on public.payment_plans for select to authenticated
using (kennel_id = public.portal_kennel_id() and buyer_id = public.portal_buyer_id());

drop policy if exists mydogportal_portal_document_select on public.buyer_documents;
create policy mydogportal_portal_document_select on public.buyer_documents for select to authenticated
using (kennel_id = public.portal_kennel_id() and buyer_id = public.portal_buyer_id());

drop policy if exists mydogportal_portal_document_link_select on public.buyer_document_puppies;
create policy mydogportal_portal_document_link_select on public.buyer_document_puppies for select to authenticated
using (
  kennel_id = public.portal_kennel_id() and exists (
    select 1 from public.buyer_documents
    where buyer_documents.id = buyer_document_puppies.document_id
      and buyer_documents.kennel_id = public.portal_kennel_id()
      and buyer_documents.buyer_id = public.portal_buyer_id()
  )
);

drop policy if exists mydogportal_portal_event_select on public.events;
create policy mydogportal_portal_event_select on public.events for select to authenticated
using (
  kennel_id = public.portal_kennel_id() and (
    (related_type = 'buyers' and related_id = public.portal_buyer_id()) or
    (related_type = 'puppies' and exists (
      select 1 from public.puppies
      where puppies.id = events.related_id
        and puppies.kennel_id = public.portal_kennel_id()
        and puppies.buyer_id = public.portal_buyer_id()
    ))
  )
);

-- Storage paths are tenant-prefixed. Portal downloads continue through signed
-- server routes; only kennel members receive direct object access here.
drop policy if exists mydogportal_member_documents_select on storage.objects;
create policy mydogportal_member_documents_select on storage.objects for select to authenticated
using (
  bucket_id = 'documents' and (storage.foldername(name))[1] = 'kennels'
  and exists (
    select 1 from public.kennels
    where kennels.id::text = (storage.foldername(name))[2]
      and public.is_kennel_member(kennels.id)
  )
);

drop policy if exists mydogportal_member_documents_insert on storage.objects;
create policy mydogportal_member_documents_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'documents' and (storage.foldername(name))[1] = 'kennels'
  and exists (
    select 1 from public.kennels
    where kennels.id::text = (storage.foldername(name))[2]
      and public.is_kennel_member(kennels.id)
  )
);

drop policy if exists mydogportal_member_documents_update on storage.objects;
create policy mydogportal_member_documents_update on storage.objects for update to authenticated
using (
  bucket_id = 'documents' and (storage.foldername(name))[1] = 'kennels'
  and exists (
    select 1 from public.kennels
    where kennels.id::text = (storage.foldername(name))[2]
      and public.is_kennel_member(kennels.id)
  )
) with check (
  bucket_id = 'documents' and (storage.foldername(name))[1] = 'kennels'
  and exists (
    select 1 from public.kennels
    where kennels.id::text = (storage.foldername(name))[2]
      and public.is_kennel_member(kennels.id)
  )
);

drop policy if exists mydogportal_member_documents_delete on storage.objects;
create policy mydogportal_member_documents_delete on storage.objects for delete to authenticated
using (
  bucket_id = 'documents' and (storage.foldername(name))[1] = 'kennels'
  and exists (
    select 1 from public.kennels
    where kennels.id::text = (storage.foldername(name))[2]
      and public.is_kennel_member(kennels.id)
  )
);
