-- MyDogPortal platform support desk.
-- This is deliberately separate from family-to-breeder Puppy Portal requests
-- and from setup/add-on fulfillment events.

create table if not exists public.platform_support_tickets (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  requester_user_id text not null,
  subject text not null check (char_length(subject) between 3 and 160),
  category text not null check (category in ('Account', 'Billing', 'Technical', 'Website', 'Domain & Email', 'Phone', 'Puppy Portal', 'Data', 'Other')),
  priority text not null default 'Normal' check (priority in ('Low', 'Normal', 'High', 'Urgent')),
  status text not null default 'Open' check (status in ('Open', 'In Progress', 'Waiting on Breeder', 'Resolved', 'Closed')),
  description text not null check (char_length(description) between 5 and 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_reply_at timestamptz,
  closed_at timestamptz
);

create table if not exists public.platform_support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.platform_support_tickets(id) on delete cascade,
  kennel_id uuid not null references public.kennels(id) on delete cascade,
  author_type text not null check (author_type in ('breeder', 'platform_admin')),
  author_user_id text not null,
  author_label text not null,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists platform_support_tickets_kennel_created_idx
  on public.platform_support_tickets(kennel_id, created_at desc);
create index if not exists platform_support_tickets_status_updated_idx
  on public.platform_support_tickets(status, updated_at desc);
create index if not exists platform_support_ticket_messages_ticket_idx
  on public.platform_support_ticket_messages(ticket_id, created_at);

alter table public.platform_support_tickets enable row level security;
alter table public.platform_support_ticket_messages enable row level security;

grant select, insert, update on table public.platform_support_tickets to authenticated;
grant select, insert on table public.platform_support_ticket_messages to authenticated;
grant usage, select on sequence public.platform_support_tickets_id_seq to authenticated;
grant usage, select on sequence public.platform_support_ticket_messages_id_seq to authenticated;

drop policy if exists mydogportal_support_ticket_select on public.platform_support_tickets;
create policy mydogportal_support_ticket_select on public.platform_support_tickets for select to authenticated
using (public.is_kennel_member(kennel_id));

drop policy if exists mydogportal_support_ticket_insert on public.platform_support_tickets;
create policy mydogportal_support_ticket_insert on public.platform_support_tickets for insert to authenticated
with check (public.is_kennel_member(kennel_id));

drop policy if exists mydogportal_support_ticket_update on public.platform_support_tickets;
create policy mydogportal_support_ticket_update on public.platform_support_tickets for update to authenticated
using (public.is_kennel_member(kennel_id)) with check (public.is_kennel_member(kennel_id));

drop policy if exists mydogportal_support_message_select on public.platform_support_ticket_messages;
create policy mydogportal_support_message_select on public.platform_support_ticket_messages for select to authenticated
using (public.is_kennel_member(kennel_id));

drop policy if exists mydogportal_support_message_insert on public.platform_support_ticket_messages;
create policy mydogportal_support_message_insert on public.platform_support_ticket_messages for insert to authenticated
with check (
  public.is_kennel_member(kennel_id)
  and author_type = 'breeder'
  and exists (
    select 1 from public.platform_support_tickets ticket
    where ticket.id = ticket_id and ticket.kennel_id = platform_support_ticket_messages.kennel_id
  )
);
