-- MyDogPortal breeder-domain expansion.
-- Extends existing system-of-record tables and adds only one-to-many history tables.

alter table dogs add column if not exists breed text;
alter table dogs add column if not exists markings text;
alter table dogs add column if not exists coat_type text;
alter table dogs add column if not exists breeder_name text;
alter table dogs add column if not exists owner_name text;
alter table dogs add column if not exists sire_id bigint references dogs(id) on delete set null;
alter table dogs add column if not exists dam_id bigint references dogs(id) on delete set null;

alter table litters add column if not exists pregnancy_status text not null default 'Unknown';
alter table litters add column if not exists pregnancy_confirmed_date date;
alter table litters add column if not exists ultrasound_date date;
alter table litters add column if not exists xray_date date;
alter table litters add column if not exists whelping_started_at timestamptz;
alter table litters add column if not exists whelping_completed_at timestamptz;

alter table puppies add column if not exists birth_time time;
alter table puppies add column if not exists markings text;
alter table puppies add column if not exists coat_type text;
alter table puppies add column if not exists collar_color text;
alter table puppies add column if not exists placenta_observed boolean;
alter table puppies add column if not exists nursing_status text;
-- Existing Puppy records treat birth_weight as pounds, so preserve that default.
-- Whelping Mode writes its explicitly selected unit (oz by default) for new births.
alter table puppies add column if not exists birth_weight_unit text not null default 'lb';

alter table buyers add column if not exists preferred_coat_type text;

create table if not exists heat_cycles (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  dog_id bigint not null references dogs(id) on delete cascade,
  start_date date not null,
  end_date date,
  predicted_next_heat date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);

create table if not exists progesterone_tests (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  dog_id bigint not null references dogs(id) on delete cascade,
  heat_cycle_id bigint references heat_cycles(id) on delete set null,
  tested_at timestamptz not null,
  result numeric(10,3) not null,
  units text not null default 'ng/mL',
  laboratory text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (result >= 0)
);

create table if not exists breeding_attempts (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  litter_id bigint references litters(id) on delete cascade,
  dam_id bigint not null references dogs(id) on delete restrict,
  sire_id bigint not null references dogs(id) on delete restrict,
  heat_cycle_id bigint references heat_cycles(id) on delete set null,
  attempted_at timestamptz not null,
  method text not null default 'Natural',
  status text not null default 'Recorded',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (dam_id <> sire_id)
);

create table if not exists genetic_tests (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  dog_id bigint not null references dogs(id) on delete cascade,
  condition text not null,
  gene text,
  result_status text not null check (result_status in ('Clear', 'Carrier', 'Affected', 'At Risk', 'Indeterminate', 'Not Tested')),
  inheritance_mode text not null default 'Autosomal Recessive',
  provider text,
  result_date date,
  laboratory_reference text,
  dog_document_id bigint references dog_documents(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists puppy_weight_logs (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  measured_at timestamptz not null default now(),
  weight numeric(12,4) not null check (weight > 0),
  unit text not null default 'oz' check (unit in ('oz', 'lb', 'g', 'kg')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists puppy_care_records (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  care_type text not null,
  title text not null,
  care_date date not null,
  product text,
  lot_number text,
  provider text,
  next_due_date date,
  notes text,
  visible_in_portal boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists waitlist_entries (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  buyer_id bigint not null references buyers(id) on delete cascade,
  litter_id bigint references litters(id) on delete set null,
  preferred_sex text,
  preferred_color text,
  preferred_coat_type text,
  other_preferences text,
  deposit_status text not null default 'Not received',
  priority_rank integer not null default 0,
  picking_position integer,
  status text not null default 'Waiting' check (status in ('Waiting', 'Ready to Pick', 'Puppy Assigned', 'Passed', 'Next Litter', 'On Hold', 'Completed', 'Removed')),
  assigned_puppy_id bigint references puppies(id) on delete set null,
  retain_priority boolean not null default true,
  joined_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (picking_position is null or picking_position > 0)
);

create table if not exists waitlist_history (
  id bigint generated by default as identity primary key,
  kennel_id uuid not null references kennels(id) on delete cascade,
  waitlist_entry_id bigint not null references waitlist_entries(id) on delete cascade,
  action text not null,
  from_position integer,
  to_position integer,
  from_status text,
  to_status text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists dogs_sire_idx on dogs(sire_id);
create index if not exists dogs_dam_idx on dogs(dam_id);
create index if not exists heat_cycles_kennel_dog_idx on heat_cycles(kennel_id, dog_id, start_date desc);
create index if not exists progesterone_tests_kennel_dog_idx on progesterone_tests(kennel_id, dog_id, tested_at desc);
create index if not exists breeding_attempts_kennel_litter_idx on breeding_attempts(kennel_id, litter_id, attempted_at desc);
create index if not exists genetic_tests_kennel_dog_idx on genetic_tests(kennel_id, dog_id, condition);
create index if not exists puppy_weight_logs_kennel_puppy_idx on puppy_weight_logs(kennel_id, puppy_id, measured_at desc);
create index if not exists puppy_care_records_kennel_puppy_idx on puppy_care_records(kennel_id, puppy_id, care_date desc);
create index if not exists waitlist_entries_kennel_position_idx on waitlist_entries(kennel_id, status, picking_position, priority_rank);
create index if not exists waitlist_history_entry_idx on waitlist_history(kennel_id, waitlist_entry_id, created_at desc);
create unique index if not exists waitlist_entries_general_buyer_idx on waitlist_entries(kennel_id, buyer_id) where litter_id is null and status not in ('Completed', 'Removed');
create unique index if not exists waitlist_entries_litter_buyer_idx on waitlist_entries(kennel_id, buyer_id, litter_id) where litter_id is not null and status not in ('Completed', 'Removed');

-- Direct Supabase access is tenant-isolated too. Server-side service-role requests
-- continue to work because service-role bypasses RLS, while authenticated clients
-- can only operate on kennels where they are an explicit member.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'dogs', 'dog_medical_records', 'dog_registrations', 'dog_documents',
    'buyers', 'litters', 'puppies', 'payment_plans', 'payment_plan_puppies',
    'transactions', 'buyer_documents', 'buyer_document_puppies', 'events', 'puppy_updates',
    'heat_cycles', 'progesterone_tests', 'breeding_attempts', 'genetic_tests',
    'puppy_weight_logs', 'puppy_care_records', 'waitlist_entries', 'waitlist_history'
  ]
  loop
    execute format('alter table %I enable row level security', table_name);
    execute format('drop policy if exists "kennel members manage rows" on %I', table_name);
    execute format(
      'create policy "kennel members manage rows" on %I for all to authenticated using (exists (select 1 from kennel_members km where km.kennel_id = %I.kennel_id and km.auth_user_id = auth.uid())) with check (exists (select 1 from kennel_members km where km.kennel_id = %I.kennel_id and km.auth_user_id = auth.uid()))',
      table_name, table_name, table_name
    );
  end loop;
end $$;

-- Atomic waitlist assignment keeps the buyer, puppy, and audit record in sync.
create or replace function assign_waitlist_puppy(
  p_kennel_id uuid,
  p_entry_id bigint,
  p_puppy_id bigint,
  p_actor uuid default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  entry_record waitlist_entries%rowtype;
  puppy_record puppies%rowtype;
begin
  select * into entry_record from waitlist_entries where id = p_entry_id and kennel_id = p_kennel_id for update;
  if not found then raise exception 'Waitlist entry was not found in this kennel.'; end if;

  select * into puppy_record from puppies where id = p_puppy_id and kennel_id = p_kennel_id for update;
  if not found then raise exception 'Puppy was not found in this kennel.'; end if;
  if puppy_record.buyer_id is not null and puppy_record.buyer_id <> entry_record.buyer_id then
    raise exception 'This puppy is already assigned to another family.';
  end if;

  update puppies
  set buyer_id = entry_record.buyer_id, status = 'Reserved', updated_at = now()::text
  where id = p_puppy_id and kennel_id = p_kennel_id;

  update buyers
  set application_status = 'Matched', updated_at = now()::text
  where id = entry_record.buyer_id and kennel_id = p_kennel_id;

  update waitlist_entries
  set status = 'Puppy Assigned', assigned_puppy_id = p_puppy_id, updated_at = now()
  where id = p_entry_id and kennel_id = p_kennel_id;

  insert into waitlist_history (
    kennel_id, waitlist_entry_id, action, from_position, to_position,
    from_status, to_status, notes, created_by
  ) values (
    p_kennel_id, p_entry_id, 'Puppy assigned', entry_record.picking_position,
    entry_record.picking_position, entry_record.status, 'Puppy Assigned',
    'Puppy #' || p_puppy_id || ' assigned to buyer #' || entry_record.buyer_id, p_actor
  );
end;
$$;

create or replace function move_waitlist_entry(
  p_kennel_id uuid,
  p_entry_id bigint,
  p_direction integer,
  p_actor uuid default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_entry waitlist_entries%rowtype;
  swap_entry waitlist_entries%rowtype;
  target_position integer;
begin
  if p_direction not in (-1, 1) then raise exception 'Direction must be -1 or 1.'; end if;
  select * into current_entry from waitlist_entries where id = p_entry_id and kennel_id = p_kennel_id for update;
  if not found then raise exception 'Waitlist entry was not found in this kennel.'; end if;
  if current_entry.picking_position is null then raise exception 'This waitlist entry has no picking position.'; end if;

  select * into swap_entry
  from waitlist_entries
  where kennel_id = p_kennel_id
    and id <> p_entry_id
    and status not in ('Completed', 'Removed')
    and ((p_direction = -1 and picking_position < current_entry.picking_position)
      or (p_direction = 1 and picking_position > current_entry.picking_position))
  order by case when p_direction = -1 then picking_position end desc,
           case when p_direction = 1 then picking_position end asc
  limit 1
  for update;

  if not found then return; end if;
  target_position := swap_entry.picking_position;
  update waitlist_entries set picking_position = current_entry.picking_position, updated_at = now() where id = swap_entry.id and kennel_id = p_kennel_id;
  update waitlist_entries set picking_position = target_position, updated_at = now() where id = current_entry.id and kennel_id = p_kennel_id;
  insert into waitlist_history (kennel_id, waitlist_entry_id, action, from_position, to_position, from_status, to_status, created_by)
  values (p_kennel_id, current_entry.id, 'Picking order changed', current_entry.picking_position, target_position, current_entry.status, current_entry.status, p_actor);
end;
$$;

create or replace function sync_breeding_calendar(
  p_kennel_id uuid,
  p_litter_id bigint,
  p_breeding_date date
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from litters where id = p_litter_id and kennel_id = p_kennel_id) then
    raise exception 'Litter was not found in this kennel.';
  end if;

  delete from events
  where kennel_id = p_kennel_id and related_type = 'litter' and related_id = p_litter_id
    and notes like '[AUTO:BREEDING]%';

  if p_breeding_date is null then return; end if;

  insert into events (kennel_id, title, event_type, event_date, related_type, related_id, status, notes, created_at, updated_at)
  values
    (p_kennel_id, 'Ultrasound window opens', 'Pregnancy', (p_breeding_date + 25)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +25 days', now()::text, now()::text),
    (p_kennel_id, 'Mid-pregnancy check-in', 'Pregnancy', (p_breeding_date + 30)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +30 days', now()::text, now()::text),
    (p_kennel_id, 'Prepare whelping supplies', 'Whelping prep', (p_breeding_date + 45)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +45 days', now()::text, now()::text),
    (p_kennel_id, 'X-ray / puppy-count window', 'Pregnancy', (p_breeding_date + 55)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +55 days', now()::text, now()::text),
    (p_kennel_id, 'Expected whelping window begins', 'Whelping', (p_breeding_date + 58)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +58 days', now()::text, now()::text),
    (p_kennel_id, 'Estimated due date', 'Whelping', (p_breeding_date + 63)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +63 days', now()::text, now()::text),
    (p_kennel_id, 'Expected whelping window ends', 'Whelping', (p_breeding_date + 65)::text, 'litter', p_litter_id, 'Scheduled', '[AUTO:BREEDING] +65 days', now()::text, now()::text);
end;
$$;

revoke all on function assign_waitlist_puppy(uuid, bigint, bigint, uuid) from public, anon, authenticated;
revoke all on function move_waitlist_entry(uuid, bigint, integer, uuid) from public, anon, authenticated;
revoke all on function sync_breeding_calendar(uuid, bigint, date) from public, anon, authenticated;
grant execute on function assign_waitlist_puppy(uuid, bigint, bigint, uuid) to service_role;
grant execute on function move_waitlist_entry(uuid, bigint, integer, uuid) to service_role;
grant execute on function sync_breeding_calendar(uuid, bigint, date) to service_role;
