"use client";

import Link from "next/link";
import { type CSSProperties, useMemo, useState } from "react";
import {
  Baby, CalendarDays, ChartNoAxesCombined, ChevronRight, ClipboardCheck, Copy, Dog, Eye,
  EyeOff, FlaskConical, FolderOpen, Globe2, Headphones, HeartPulse, Image as ImageIcon,
  LayoutDashboard, ListOrdered, ListTree, Mail, Menu, MessageSquareText, MonitorSmartphone,
  PackageSearch, Palette, PawPrint, Plus, ReceiptText, RefreshCw, Route, Save, Search, Settings2,
  ShieldCheck, Sparkles, UserRound, UsersRound, WalletCards, X, type LucideIcon,
} from "lucide-react";
import { ApplicationBuilder } from "../../../components/application-builder";
import { defaultApplicationFormConfig, type ApplicationFormConfig } from "../../../lib/application-form";
import type { DemoKennel } from "./demo-data";
import "../../puppies/website/puppy-website.css";
import "./real-demo.css";
import "./real-builder.css";

type View = "Command" | "Calendar" | "Breeding" | "Breedings" | "Litters" | "Whelping" | "Puppies" | "Care" | "Applications" | "Families" | "Waitlist" | "Placement" | "Delivery" | "Finance" | "Inventory" | "Comms" | "Templates" | "Reports" | "Portal" | "CRM" | "Vault";
type Group = "Kennel day" | "Breeding" | "Puppy families" | "Business" | "Operations";
type NavItem = { id: View; label: string; icon: LucideIcon; group: Group };
type PuppyBuilderConfig = {
  enabled: boolean; title: string; introduction: string; layout: "cards" | "compact";
  primaryColor: string; accentColor: string; showPrice: boolean; showBirthDate: boolean;
  showSex: boolean; showColor: boolean; showCoat: boolean; showMarkings: boolean;
  applicationLabel: string; applicationUrl: string; allowedOrigins: string[]; hiddenPuppyIds: number[];
};

const nav: NavItem[] = [
  { id: "Command", label: "Daily overview", icon: LayoutDashboard, group: "Kennel day" },
  { id: "Calendar", label: "Kennel calendar", icon: CalendarDays, group: "Kennel day" },
  { id: "Breeding", label: "Dogs", icon: Dog, group: "Breeding" },
  { id: "Breedings", label: "Breedings", icon: FlaskConical, group: "Breeding" },
  { id: "Litters", label: "Litters", icon: ListTree, group: "Breeding" },
  { id: "Whelping", label: "Whelping", icon: Baby, group: "Breeding" },
  { id: "Puppies", label: "Puppies", icon: PawPrint, group: "Breeding" },
  { id: "Care", label: "Health records", icon: HeartPulse, group: "Breeding" },
  { id: "Applications", label: "Puppy applications", icon: ClipboardCheck, group: "Puppy families" },
  { id: "Families", label: "Families & waitlist", icon: UsersRound, group: "Puppy families" },
  { id: "Waitlist", label: "Waitlist", icon: ListOrdered, group: "Puppy families" },
  { id: "Placement", label: "Puppy matching", icon: UserRound, group: "Puppy families" },
  { id: "Delivery", label: "Go-home planning", icon: Route, group: "Puppy families" },
  { id: "Finance", label: "Sales & payments", icon: WalletCards, group: "Business" },
  { id: "Inventory", label: "Kennel expenses", icon: PackageSearch, group: "Business" },
  { id: "Reports", label: "Reports", icon: ChartNoAxesCombined, group: "Business" },
  { id: "Comms", label: "Family messages", icon: Mail, group: "Operations" },
  { id: "Templates", label: "Templates & automation", icon: MessageSquareText, group: "Operations" },
  { id: "Portal", label: "Family portal", icon: MonitorSmartphone, group: "Operations" },
  { id: "CRM", label: "Phone center", icon: Headphones, group: "Operations" },
  { id: "Vault", label: "Documents", icon: FolderOpen, group: "Operations" },
];

const groups: Group[] = ["Kennel day", "Breeding", "Puppy families", "Business", "Operations"];
const groupIcons: Record<Group, LucideIcon> = { "Kennel day": LayoutDashboard, Breeding: Dog, "Puppy families": PawPrint, Business: WalletCards, Operations: FolderOpen };
const copy: Record<View, { title: string; text: string }> = {
  Command: { title: "Today at a glance", text: "The same command-center layout breeders use in the live MyDogPortal OS." },
  Calendar: { title: "Schedule", text: "Breeding, whelping, care, family calls, pickup, delivery, and follow-up work." },
  Breeding: { title: "Dogs", text: "Breeding dogs, identity, registrations, health records, pedigree, and status." },
  Breedings: { title: "Breedings & test mating", text: "Heat cycles, progesterone, planned pairings, pedigree context, pregnancy milestones, and due dates." },
  Litters: { title: "Litters", text: "Every litter from pairing through whelping, puppy roster, and placement." },
  Whelping: { title: "Whelping Mode", text: "A focused birth workflow for newborn identity, birth weights, nursing, placenta, and daily care." },
  Puppies: { title: "Puppies", text: "Identity, growth, care, availability, pricing, family assignment, and live website publishing." },
  Care: { title: "Health & care", text: "Medical schedules, puppy milestones, recurring care, and kennel work." },
  Applications: { title: "Applications", text: "Screen families, customize intake questions, publish the form, approve homes, and build the waitlist." },
  Families: { title: "Buyers & waitlist", text: "Contact, preferences, assigned puppies, payments, documents, and portal access." },
  Waitlist: { title: "Waitlist & picking order", text: "Approved families, deposit state, queue history, passes, and puppy selection." },
  Placement: { title: "Puppy placement", text: "Match approved families to puppies and carry placement into payment and contract work." },
  Delivery: { title: "Pickup & delivery", text: "Final balances, signed documents, handoff schedules, and go-home readiness." },
  Finance: { title: "Payments & sales", text: "Deposits, payments, balances, payment plans, receipts, and sale revenue." },
  Inventory: { title: "Costs & expenses", text: "Veterinary, breeding, supply, travel, and kennel costs against recorded sales." },
  Comms: { title: "Family communications", text: "Updates, calls, messages, requests, and communication history." },
  Templates: { title: "Automations & templates", text: "Business language, document templates, automatic emails, and puppy milestones." },
  Reports: { title: "Reports and intelligence", text: "Program performance, profitability, placement progress, and operating snapshots." },
  Portal: { title: "Puppy Portal simulator", text: "The breeder view of exactly what each family sees in its private portal." },
  CRM: { title: "Caller CRM", text: "Caller identity, family account context, assigned puppy, payments, and conversation history." },
  Vault: { title: "Documents", text: "Buyer files, dog records, certificates, signed agreements, and generated packets." },
};

const puppyNames = ["Clover", "Biscuit", "Maple", "Scout", "Piper", "Nova", "Moss", "Sunny", "Rook", "Hex"];

function DemoDashboard({ kennel, onNavigate, onAction }: { kennel: DemoKennel; onNavigate: (view: View) => void; onAction: () => void }) {
  const metrics = [
    ["Active litters", "1", kennel.breeding.stage, "Litters", ListTree],
    ["Puppies", String(kennel.litter.puppies), `${kennel.litter.reserved} reserved`, "Puppies", PawPrint],
    ["Applications", "4", "Waiting for review", "Applications", ClipboardCheck],
    ["Next 30 days", "4", kennel.litter.next, "Calendar", CalendarDays],
    ["Payments due", "$3,700", "$8,450 received this month", "Finance", WalletCards],
  ] as const;
  return <div className="bos-today">
    <header className="dashboard-command-header"><div className="dashboard-command-copy"><span>KENNEL COMMAND CENTER</span><h1>Today at a glance</h1><p>Saturday, August 8 · {kennel.name}</p><div className="dashboard-day-meta"><span className="needs-work"><i/><b>3 items need attention</b></span><span><CalendarDays size={13}/> 4 next 30 days</span><span><PawPrint size={13}/> {kennel.litter.puppies} active puppies</span></div></div><div className="dashboard-quick-actions"><button onClick={onAction}><CalendarDays size={16}/> Schedule</button><button onClick={onAction}><ReceiptText size={16}/> Payment</button><button className="primary-action" onClick={onAction}><Plus size={16}/> Quick add</button></div></header>
    <section className="dashboard-metrics">{metrics.map(([label, value, detail, target, Icon]) => <button key={label} onClick={() => onNavigate(target)}><span className="dashboard-metric-icon"><Icon size={17}/></span><span><small>{label}</small><b>{value}</b><em>{detail}</em></span><ChevronRight size={15}/></button>)}</section>
    <div className="dashboard-primary-grid"><section className="dashboard-section dashboard-attention"><header><div><span>NEEDS ATTENTION</span><h2>What should move next</h2></div><strong className="has-work">3</strong></header><div className="dashboard-attention-list"><button onClick={() => onNavigate("Breedings")}><em className="urgent">BREEDING</em><span><b>{kennel.breeding.dam} · {kennel.breeding.stage}</b><small>{kennel.breeding.due}</small></span><ChevronRight size={16}/></button><button onClick={() => onNavigate("Comms")}><em className="next">FAMILY</em><span><b>Family update day</b><small>{kennel.litter.name} · publish photos and weights</small></span><ChevronRight size={16}/></button><button onClick={() => onNavigate("Vault")}><em className="review">DOCUMENT</em><span><b>1 family document awaiting signature</b><small>Review the family document queue</small></span><ChevronRight size={16}/></button></div></section><section className="dashboard-section dashboard-upcoming"><header><div><span>UPCOMING</span><h2>Breeding calendar</h2></div><button onClick={() => onNavigate("Calendar")}>Open calendar</button></header><div className="dashboard-event-list">{[["12","Aug","Family update day","Updates · scheduled"],["19","Aug","Puppy care milestone",kennel.litter.next],["25","Aug","Whelping preparation",kennel.breeding.due]].map(([day, month, title, detail]) => <button key={title} onClick={() => onNavigate("Calendar")}><time><b>{day}</b><small>{month}</small></time><span><b>{title}</b><small>{detail}</small></span><em>Scheduled</em></button>)}</div></section></div>
    <section className="dashboard-section dashboard-program"><header><div><span>ACTIVE PROGRAM</span><h2>Litters and pregnancies in motion</h2></div><button onClick={() => onNavigate("Breedings")}>Breeding workspace <ChevronRight size={14}/></button></header><div className="real-demo-program-grid"><article><small>ACTIVE LITTER</small><h3>{kennel.litter.name}</h3><strong>{kennel.litter.puppies}</strong><p>{kennel.litter.reserved} reserved · born {kennel.litter.born}</p></article><article><small>ACTIVE BREEDING</small><h3>{kennel.breeding.dam} × {kennel.breeding.sire}</h3><strong>{kennel.breeding.stage}</strong><p>{kennel.breeding.due} · {kennel.breeding.coi}</p></article><article><small>FAMILY JOURNEY</small><h3>Placement pipeline</h3><strong>{kennel.families.length + 9}</strong><p>Application → approval → match → go-home</p></article></div></section>
  </div>;
}

function ApplicationInbox({ kennel, onAction }: { kennel: DemoKennel; onAction: () => void }) {
  return <div className="applications-grid real-demo-applications-grid"><section className="applications-panel"><div className="panel-title"><span>Application queue</span><h2>4 families</h2></div><div className="application-list">{[...kennel.families, { name: "Taylor Bennett", puppy: "Not assigned", stage: "New application", balance: "Not invoiced" }].map((family, index) => <article className="application-card" key={family.name}><button className="application-main" onClick={onAction}><b>{family.name}</b><small>{index === 3 ? "taylor@example.com · Richmond, VA" : `${family.stage} · ${family.puppy}`}</small><span className={`status ${index === 0 ? "approved" : ""}`}>{index === 3 ? "New" : index === 0 ? "Approved" : "Review"}</span></button><div className="application-actions"><button className={index === 3 ? "approve" : ""} onClick={onAction}>{index === 3 ? "Approve" : "Review"}</button></div></article>)}</div></section><aside className="applications-panel"><div className="panel-title"><span>Selected family</span><h2>Taylor Bennett</h2></div><div className="detail-body"><dl><dt>Status</dt><dd><span className="status">New</span></dd><dt>Email</dt><dd>taylor@example.com</dd><dt>Phone</dt><dd>(276) 555-0148</dd><dt>Location</dt><dd>Richmond, Virginia</dd><dt>Preferences</dt><dd>Female / no color preference</dd><dt>Assigned puppy</dt><dd>No puppy assigned</dd></dl><section className="application-answers"><header><small>SUBMITTED ANSWERS</small><h3>{kennel.name} Puppy Application</h3></header><div className="application-answer"><small>Household · Puppy&apos;s primary caregiver</small><b>Two-adult home; flexible work schedule and prior breed experience.</b></div><div className="application-answer"><small>Puppy preferences · Temperament and lifestyle fit</small><b>Confident family companion with moderate activity needs.</b></div></section><div className="detail-actions"><button className="primary" onClick={onAction}><ShieldCheck size={16}/> Approve application</button><button onClick={onAction}>Move to wait list</button></div></div></aside></div>;
}

function PuppyWebsiteBuilderDemo({ kennel, onNotice }: { kennel: DemoKennel; onNotice: (message?: string) => void }) {
  const [config, setConfig] = useState<PuppyBuilderConfig>({ enabled: true, title: "Available Puppies", introduction: `Meet the puppies currently available from ${kennel.name}. Availability changes as approved families are matched.`, layout: "cards", primaryColor: kennel.accentDark, accentColor: kennel.accent, showPrice: true, showBirthDate: true, showSex: true, showColor: true, showCoat: true, showMarkings: true, applicationLabel: "Apply for a Puppy", applicationUrl: "", allowedOrigins: [`https://${kennel.websiteLabel}`], hiddenPuppyIds: [] });
  const puppies = puppyNames.slice(0, kennel.litter.puppies).map((name, index) => ({ id: index + 1, name, sex: index % 2 ? "Female" : "Male", color: index % 2 ? "Cream sable" : "Black & tan", coat: index % 3 ? "Long coat" : "Smooth coat", price: 2500 + index * 100, available: index >= kennel.litter.reserved }));
  const eligible = puppies.filter((puppy) => puppy.available);
  const visible = eligible.filter((puppy) => !config.hiddenPuppyIds.includes(puppy.id));
  const origin = `https://${kennel.slug}.mydogportal.site`;
  const embedCode = `<div id="mydogportal-puppies"></div>\n<script src="${origin}/api/website/puppy-embed?kennel=${kennel.slug}" data-target="mydogportal-puppies" async></script>`;
  const patch = (values: Partial<PuppyBuilderConfig>) => setConfig((current) => ({ ...current, ...values }));
  const toggle = (id: number) => patch({ hiddenPuppyIds: config.hiddenPuppyIds.includes(id) ? config.hiddenPuppyIds.filter((value) => value !== id) : [...config.hiddenPuppyIds, id] });
  const copyValue = async (value: string, label: string) => { try { await navigator.clipboard.writeText(value); onNotice(`${label} copied. This sample remains isolated from live breeder data.`); } catch { onNotice("Clipboard access was blocked. The sample code is still visible for review."); } };
  return <div className="real-demo-puppy-builder"><div className="real-demo-builder-route"><div><small>PUPPIES / WEBSITE BUILDER</small><h2>Publish puppies from the OS to your website</h2><p>One puppy record, two surfaces. Add, edit, reserve, assign, or delete it in MyDogPortal and the connected public listing updates automatically.</p></div><button type="button" onClick={() => onNotice("Interactive demo updated for this session. No breeder or customer data was changed.")}><Save size={16}/> Save & publish</button></div><div className="puppy-builder-shell"><section className="puppy-builder-controls">
    <article className="builder-panel publish-panel"><header><span><Globe2 size={17}/></span><div><small>PUBLIC FEED</small><h2>Website publishing</h2></div><label className="builder-switch"><input type="checkbox" checked={config.enabled} onChange={(event) => patch({ enabled: event.target.checked })}/><i/><b>{config.enabled ? "Live" : "Paused"}</b></label></header><p>When live, only unassigned puppies whose OS status contains “Available” can publish. Assigned, sold, reserved, or deleted puppies automatically leave the feed.</p></article>
    <article className="builder-panel"><header><span><Settings2 size={17}/></span><div><small>CONTENT & STYLE</small><h2>Listing appearance</h2></div></header><div className="builder-form-grid"><label className="wide"><span>Heading</span><input value={config.title} onChange={(event) => patch({ title: event.target.value })}/></label><label className="wide"><span>Introduction</span><textarea rows={4} value={config.introduction} onChange={(event) => patch({ introduction: event.target.value })}/></label><label><span>Layout</span><select value={config.layout} onChange={(event) => patch({ layout: event.target.value as "cards" | "compact" })}><option value="cards">Photo cards</option><option value="compact">Compact rows</option></select></label><label><span>Primary color</span><input type="color" value={config.primaryColor} onChange={(event) => patch({ primaryColor: event.target.value })}/></label><label><span>Accent color</span><input type="color" value={config.accentColor} onChange={(event) => patch({ accentColor: event.target.value })}/></label><label className="wide"><span>Application button text</span><input value={config.applicationLabel} onChange={(event) => patch({ applicationLabel: event.target.value })}/></label><label className="wide"><span>Application URL</span><input type="url" placeholder={`${origin}/apply`} value={config.applicationUrl} onChange={(event) => patch({ applicationUrl: event.target.value })}/></label></div><div className="builder-fields-toggle">{[["showPrice","Price"],["showBirthDate","Birth date"],["showSex","Sex"],["showColor","Color"],["showCoat","Coat"],["showMarkings","Markings"]].map(([key, label]) => <label key={key}><input type="checkbox" checked={Boolean(config[key as keyof PuppyBuilderConfig])} onChange={(event) => patch({ [key]: event.target.checked })}/><span>{label}</span></label>)}</div></article>
    <article className="builder-panel"><header><span><Eye size={17}/></span><div><small>PUBLIC PUPPIES</small><h2>Choose what appears</h2></div><button type="button" className="refresh-button" onClick={() => onNotice("The sample puppy roster is already current.")}><RefreshCw size={14}/> Refresh OS</button></header><div className="builder-puppy-list">{eligible.map((puppy) => { const shown = !config.hiddenPuppyIds.includes(puppy.id); return <div key={puppy.id}><span className="builder-puppy-photo"><PawPrint size={18}/></span><p><b>{puppy.name}</b><small>{puppy.sex} · {puppy.color} · ${puppy.price.toLocaleString()}</small></p><button type="button" className={shown ? "shown" : "hidden"} onClick={() => toggle(puppy.id)}>{shown ? <Eye size={14}/> : <EyeOff size={14}/>} {shown ? "Shown" : "Hidden"}</button></div>; })}</div></article>
    <article className="builder-panel install-panel"><header><span><MonitorSmartphone size={17}/></span><div><small>WEBSITE INSTALLATION</small><h2>Embed on the breeder&apos;s website</h2></div></header><div className="install-stack"><div><b>Native live listing</b><p>Paste this into an HTML/code block. It renders responsive puppy cards and reads the latest public OS data each time the page loads.</p><textarea readOnly rows={6} value={embedCode}/><button type="button" onClick={() => void copyValue(embedCode, "Embed code")}><Copy size={14}/> Copy embed code</button></div><div><b>Headless JSON feed</b><p>For a fully custom website design, use the read-only JSON feed. No private database credentials are exposed.</p><textarea readOnly rows={3} value={`${origin}/api/website/puppies?kennel=${kennel.slug}`}/><button type="button" onClick={() => void copyValue(`${origin}/api/website/puppies?kennel=${kennel.slug}`, "Feed URL")}><Copy size={14}/> Copy feed URL</button></div><label><span>Authorized website origins</span><textarea rows={4} value={config.allowedOrigins.join("\n")} onChange={(event) => patch({ allowedOrigins: event.target.value.split(/\r?\n|,/).map((value) => value.trim()).filter(Boolean) })}/></label></div></article>
  </section><aside className="puppy-builder-preview"><div className="preview-sticky"><header><span><Sparkles size={16}/></span><div><small>LIVE PREVIEW</small><b>{visible.length} published pupp{visible.length === 1 ? "y" : "ies"}</b></div></header><section style={{ "--preview-primary": config.primaryColor, "--preview-accent": config.accentColor } as CSSProperties}><small className="preview-eyebrow">{kennel.name}</small><h2>{config.title}</h2><p>{config.introduction}</p><div className={`preview-puppies ${config.layout}`}>{visible.map((puppy) => <article key={puppy.id}><div className="preview-photo"><ImageIcon size={28}/></div><div><span><h3>{puppy.name}</h3><em>Available</em></span><ul>{config.showSex && <li>{puppy.sex}</li>}{config.showColor && <li>{puppy.color}</li>}{config.showCoat && <li>{puppy.coat}</li>}{config.showBirthDate && <li>Born {kennel.litter.born}</li>}</ul>{config.showPrice && <strong>${puppy.price.toLocaleString()}</strong>}<button type="button" onClick={() => onNotice("In the live website, this opens the kennel's connected application.")}>{config.applicationLabel}</button></div></article>)}</div>{!visible.length && <div className="preview-empty">No puppies are currently selected for the public feed.</div>}</section></div></aside></div></div>;
}

function DemoWorkspace({ view, kennel, onAction, onNotice }: { view: View; kennel: DemoKennel; onAction: () => void; onNotice: (message?: string) => void }) {
  const [applicationMode, setApplicationMode] = useState<"inbox" | "builder">("inbox");
  const [puppyMode, setPuppyMode] = useState<"records" | "builder">("records");
  const [applicationConfig, setApplicationConfig] = useState<ApplicationFormConfig>(() => ({ ...defaultApplicationFormConfig, title: `${kennel.name} Puppy Application`, allowedOrigins: [`https://${kennel.websiteLabel}`], fields: defaultApplicationFormConfig.fields.map((field) => ({ ...field, options: [...field.options] })) }));

  if (view === "Applications") return <div className="real-demo-module-workspace"><div className="application-modes real-demo-mode-tabs" aria-label="Application workspace"><button type="button" className={applicationMode === "inbox" ? "active" : ""} onClick={() => setApplicationMode("inbox")}><ClipboardCheck size={15}/> Application inbox</button><button type="button" className={applicationMode === "builder" ? "active" : ""} onClick={() => setApplicationMode("builder")}><Settings2 size={15}/> Builder + website embed</button></div>{applicationMode === "builder" ? <ApplicationBuilder key={`${kennel.slug}-${applicationConfig.updatedAt || "demo"}`} config={applicationConfig} onSaved={setApplicationConfig} demoMode demoTenant={{ slug: kennel.slug, name: kennel.name, websiteUrl: kennel.websiteLabel }}/> : <ApplicationInbox kennel={kennel} onAction={onAction}/>}</div>;
  if (view === "Puppies") return <div className="real-demo-module-workspace"><div className="application-modes real-demo-mode-tabs" aria-label="Puppy workspace"><button type="button" className={puppyMode === "records" ? "active" : ""} onClick={() => setPuppyMode("records")}><PawPrint size={15}/> Puppy records</button><button type="button" className={puppyMode === "builder" ? "active" : ""} onClick={() => setPuppyMode("builder")}><Globe2 size={15}/> Puppy Website Builder</button></div>{puppyMode === "builder" ? <PuppyWebsiteBuilderDemo kennel={kennel} onNotice={onNotice}/> : <PuppyRoster kennel={kennel} onAction={onAction}/>}</div>;
  if (view === "Breeding") return <div className="real-demo-view-grid">{kennel.dogs.map((dog) => <article className="dashboard-section real-demo-card" key={dog.name}><header><div><span>{dog.role.toUpperCase()}</span><h2>{dog.name}</h2></div><Dog size={19}/></header><div className="real-demo-card-body"><b>{dog.status}</b><p>{dog.detail}</p><div><span>Pedigree on file</span><span>Health current</span><span>Genetics recorded</span></div></div></article>)}</div>;
  if (view === "Litters" || view === "Whelping") return <PuppyRoster kennel={kennel} onAction={onAction}/>;
  if (["Families", "Waitlist", "Placement", "Delivery"].includes(view)) return <section className="dashboard-section"><header><div><span>FAMILY JOURNEY</span><h2>Placement pipeline</h2></div><button onClick={onAction}>New family</button></header><div className="real-demo-family-table"><header><span>Family</span><span>Puppy</span><span>Stage</span><span>Balance</span></header>{kennel.families.map((family) => <div key={family.name}><span><b>{family.name}</b><small>Approved family</small></span><span>{family.puppy}</span><span>{family.stage}</span><span><b>{family.balance}</b></span></div>)}</div></section>;
  if (view === "Finance" || view === "Inventory" || view === "Reports") return <><section className="dashboard-metrics real-demo-finance"><button><span className="dashboard-metric-icon"><WalletCards size={17}/></span><span><small>Received this month</small><b>$8,450</b><em>12 recorded payments</em></span></button><button><span className="dashboard-metric-icon"><ReceiptText size={17}/></span><span><small>Outstanding</small><b>$3,700</b><em>Across 3 families</em></span></button><button><span className="dashboard-metric-icon"><PackageSearch size={17}/></span><span><small>Program expenses</small><b>$1,126</b><em>August to date</em></span></button></section><section className="dashboard-section"><header><div><span>FINANCIAL ACTIVITY</span><h2>Buyer accounts</h2></div><button onClick={onAction}>Record payment</button></header><div className="real-demo-family-table"><header><span>Family</span><span>Puppy</span><span>Status</span><span>Balance</span></header>{kennel.families.map((family) => <div key={family.name}><span><b>{family.name}</b><small>Buyer account</small></span><span>{family.puppy}</span><span>{family.balance === "Paid" ? "Paid" : "Open"}</span><span><b>{family.balance}</b></span></div>)}</div></section></>;
  const cards: Record<string, Array<[string, string, string]>> = {
    Breedings: [["ACTIVE BREEDING", `${kennel.breeding.dam} × ${kennel.breeding.sire}`, kennel.breeding.stage], ["PROGESTERONE", kennel.breeding.progesterone, "Recorded on the breeding timeline"], ["PEDIGREE", kennel.breeding.coi, "Common ancestors and pairing context"]],
    Calendar: [["NEXT", "Family update day", "Aug 12 · photos + weights"], ["PUPPY CARE", kennel.litter.next, "Automatic age-based milestone"], ["WHELPING", kennel.breeding.due, "Preparation checklist available"]],
    Care: [["HEALTH RECORDS", "Vaccines & prevention", "Dog and puppy care schedules"], ["WEIGHTS", "Growth monitoring", "Newborn and puppy trends"], ["REMINDERS", "Upcoming care", "Tasks surface on the command center"]],
    Comms: [["FAMILY UPDATE", "Weekly puppy update", "Photos, weight, and milestone message"], ["AUTOMATIC EMAIL", "Application received", "Editable business language"], ["MESSAGE HISTORY", "Private family record", "Calls, updates, and requests together"]],
    Templates: [["DOCUMENTS", "Bill of Sale + Health Guarantee", "Auto-populated from family and puppy data"], ["EMAILS", "Automatic family communications", "Editable templates and triggers"], ["MILESTONES", "Weekly puppy milestones", "Scheduled by puppy age"]],
    Portal: [["FAMILY PORTAL", "Private buyer account", "Puppy, payments, documents, updates"], ["DOCUMENTS", "Signed copies", "Available after completion"], ["PUPPY JOURNEY", "Milestones & weights", "Updates appear automatically"]],
    CRM: [["PHONE CENTER", "Caller-aware account context", "Family record appears with the call"], ["REQUESTS", "Callback & message history", "Connected to the family account"], ["BUSINESS VOICE", "IVR and call routing", "Configured per kennel"]],
    Vault: [["BUYER DOCUMENTS", "Signed agreements", "Stored with the family record"], ["DOG RECORDS", "Registrations & health", "Connected to the breeding dog"], ["PUPPY PACKETS", "Complete go-home packet", "Generated from saved data"]],
  };
  const chosen = cards[view] || [["WORKSPACE", copy[view].title, copy[view].text], ["CONNECTED RECORDS", "One source of truth", "Changes flow across the breeder OS"], ["READ-ONLY DEMO", "Sample information", "No real breeder data is connected"]];
  return <div className="real-demo-view-grid">{chosen.map(([eyebrow, title, text]) => <article className="dashboard-section real-demo-card" key={title}><header><div><span>{eyebrow}</span><h2>{title}</h2></div><Sparkles size={19}/></header><div className="real-demo-card-body"><p>{text}</p><button onClick={onAction}>Open sample action <ChevronRight size={14}/></button></div></article>)}</div>;
}

function PuppyRoster({ kennel, onAction }: { kennel: DemoKennel; onAction: () => void }) {
  return <section className="dashboard-section"><header><div><span>ACTIVE LITTER</span><h2>{kennel.litter.name}</h2></div><button onClick={onAction}>Add puppy</button></header><div className="real-demo-puppy-grid">{puppyNames.slice(0, kennel.litter.puppies).map((name, index) => <article key={name}><span className="real-demo-pup-icon"><PawPrint size={16}/></span><div><b>{name}</b><small>{index < kennel.litter.reserved ? "Reserved" : "Available"} · {index % 2 ? "Female" : "Male"}</small></div><em>{(10.8 + index * .5).toFixed(1)} oz</em></article>)}</div></section>;
}

export default function RealOSDemoClient({ kennel }: { kennel: DemoKennel }) {
  const [view, setView] = useState<View>("Command");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const active = nav.find((item) => item.id === view) || nav[0];
  const badges = useMemo(() => ({ Applications: 4, Puppies: Math.max(0, kennel.litter.puppies - kennel.litter.reserved), Calendar: 4, Finance: 2 }), [kennel]);
  const showNotice = (message = "This is a read-only sample workspace. In a real breeder account, this control opens the live form or workflow.") => { setNotice(message); window.setTimeout(() => setNotice(""), 3400); };
  const navigate = (next: View) => { setView(next); setSidebarOpen(false); };
  return <div className="real-demo-shell" style={{ "--tenant-primary": kennel.accentDark, "--tenant-accent": kennel.accent } as CSSProperties}>
    <div className="real-demo-sample-bar"><span><Sparkles size={14}/> INTERACTIVE SAMPLE WORKSPACE</span><p>Production interface · realistic demonstration records · no live breeder or family data</p><Link href={kennel.websiteHref}>Back to website example</Link></div>
    <div className="bos-shell real-demo-bos-shell"><aside className={`bos-command-bar${sidebarOpen ? " mobile-open" : ""}`}><div className="bos-sidebar-top"><button className="bos-brand" onClick={() => navigate("Command")}><span><PawPrint size={20}/></span><b>{kennel.name}</b><small>{kennel.breed} · BREEDER OS</small></button><button className="bos-nav-toggle" type="button" onClick={() => setSidebarOpen((value) => !value)}>{sidebarOpen ? <X size={20}/> : <Menu size={20}/>}</button></div><div className="bos-search"><Search size={16}/><input readOnly placeholder="Find dogs, puppies, families…" onClick={() => showNotice()}/><kbd>⌘ K</kbd></div><button className="bos-global-add" onClick={() => showNotice()}><Plus size={17}/><span>Quick add</span></button><div className="bos-sidebar-scroll"><nav className="bos-sidebar-nav">{groups.map((group) => { const GroupIcon = groupIcons[group]; return <section key={group}><h2><GroupIcon size={14}/><span>{group}</span></h2><div>{nav.filter((item) => item.group === group).map((item) => { const Icon = item.icon; const badge = Number((badges as Record<string, number>)[item.id] || 0); return <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => navigate(item.id)}><Icon size={16}/><span>{item.label}</span>{badge > 0 && <em>{badge}</em>}</button>; })}</div></section>; })}</nav><footer className="bos-sidebar-footer"><div><button onClick={() => showNotice()}><Palette size={15}/><span>Brand</span></button><button onClick={() => showNotice()}><Globe2 size={15}/><span>Domain</span></button><button onClick={() => showNotice()}><Headphones size={15}/><span>Support</span></button></div><p><i/><span><b>Sample workspace</b><small>Session-only demonstration</small></span></p></footer></div></aside><main className="bos-main">{view !== "Command" && <header className="bos-view-head"><div><small>{active.group} / {active.label}</small><h1>{copy[view].title}</h1><p>{copy[view].text}</p></div><div><button onClick={() => showNotice()}><ReceiptText size={15}/> Payment</button><button className="primary-action" onClick={() => showNotice()}><Plus size={15}/> Add to {active.label}</button></div></header>}{view === "Command" ? <DemoDashboard kennel={kennel} onNavigate={navigate} onAction={() => showNotice()}/> : <DemoWorkspace view={view} kennel={kennel} onAction={() => showNotice()} onNotice={showNotice}/>}</main></div>
    {notice && <div className="real-demo-toast"><ShieldCheck size={16}/>{notice}</div>}
  </div>;
}
