import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Award, Check, Dna, Dog, FileCheck2, Medal, ShieldCheck, Target, Waypoints } from "lucide-react";
import "../collection.css";

export const metadata: Metadata = {
  title: "Ironwood German Shepherds | MyDogPortal Website Template",
  description: "A structured working-dog German Shepherd breeder website template available through MyDogPortal.",
};

export default function IronwoodShepherdsTemplatePage() {
  return <main className="iw-site">
    <div className="template-demo"><span>MYDOGPORTAL WEBSITE TEMPLATE 05 · INCLUDED KENNEL ADDRESS</span><p><b>ironwood.mydogportal.site</b> demonstrates the included <b>yourkennel.mydogportal.site</b> address. Your kennel, dogs, training, health records, photography, colors, and policies replace the sample.</p><div className="template-demo-actions"><Link href="/templates/os-demo/ironwood-shepherds">Explore OS demo <ArrowRight size={13}/></Link><Link href="/signup?website_template=ironwood-shepherds">Choose this style <ArrowRight size={13}/></Link></div></div>
    <nav className="iw-nav"><a className="iw-brand" href="#home"><span><ShieldCheck size={20}/></span><div><b>IRONWOOD</b><small>GERMAN SHEPHERDS · WORKING WITH PURPOSE</small></div></a><div className="iw-nav-links"><a href="#standards">Standards</a><a href="#program">Program</a><a href="#dogs">Dogs</a><a href="#portal">Family Portal</a></div><div className="iw-nav-actions"><Link href="/portal/login">Sign in</Link><a className="iw-apply" href="#apply">Apply</a></div></nav>
    <section className="iw-hero" id="home"><div className="iw-hero-copy"><span className="iw-kicker"><Target size={14}/> STABLE NERVES · SOUND STRUCTURE · CLEAR PURPOSE</span><h1>Built to work.<br/><span>Raised to belong.</span></h1><p>German Shepherds selected for health, temperament, trainability, structure, and the balance required to work with confidence and live well with their people.</p><div className="iw-actions"><a href="#program">Explore our program <ArrowRight size={14}/></a><a href="#dogs">Meet the dogs</a></div></div><div className="iw-hero-photo" role="img" aria-label="German Shepherd outdoors"><aside><small>FEATURED DOG · SAMPLE PROFILE</small><b>Valko — balanced drive, clear head, family off-switch.</b></aside></div></section>
    <section className="iw-standards" id="standards"><article><Dna size={21}/><b>Genetic screening</b><p>Breed-relevant health information organized by dog.</p></article><article><Award size={21}/><b>Orthopedic testing</b><p>Publish the clearances your program chooses to share.</p></article><article><Medal size={21}/><b>Temperament</b><p>Document development, training, and working context.</p></article><article><FileCheck2 size={21}/><b>Verified records</b><p>Keep registrations, health documents, and pedigrees connected.</p></article></section>
    <section className="iw-program" id="program"><header className="iw-head"><div><span className="iw-kicker">THE IRONWOOD PROGRAM</span><h2>A structured approach to every generation.</h2></div><p>This performance-led design prioritizes health testing, working purpose, training, pedigree context, and confident typography—ideal for serious working and performance programs.</p></header><div className="iw-program-grid"><article><span><Waypoints size={21}/></span><h3>Planned pairings</h3><p>Present breeding goals, planned litters, health context, and the reason behind each pairing.</p></article><article><span><Target size={21}/></span><h3>Development</h3><p>Show how puppies build resilience, engagement, recovery, environmental confidence, and household skills.</p></article><article><span><Dog size={21}/></span><h3>Placement</h3><p>Explain how working potential, family expectations, breeder evaluation, and individual temperament guide matches.</p></article></div></section>
    <section className="iw-dogs" id="dogs"><div className="iw-dog-photo" role="img" aria-label="German Shepherd working-dog profile"/><div className="iw-dog-copy"><span className="iw-kicker">SIRE PROFILE · SAMPLE</span><h2>Valko vom Ironwood</h2><p>A sample profile demonstrates how a breeder can combine pedigree, health, training, working credentials, photos, and planned litter information in one clear public presentation.</p><div className="iw-dog-stats"><span><small>HIPS / ELBOWS</small><b>Documented</b></span><span><small>GENETICS</small><b>On file</b></span><span><small>TEMPERAMENT</small><b>Evaluated</b></span><span><small>PLANNED LITTERS</small><b>1 upcoming</b></span></div></div></section>
    <section className="iw-portal" id="portal"><div><span className="iw-kicker">PRIVATE FAMILY PORTAL</span><h2>The record follows the puppy.</h2><p>Placed families receive secure access to the information intended for them—from puppy updates and health records to documents, payments, schedule, transportation, messages, and resources.</p><ul><li><Check size={14}/> Health & growth records</li><li><Check size={14}/> Puppy updates</li><li><Check size={14}/> Documents & signatures</li><li><Check size={14}/> Payments & schedule</li></ul></div><div className="iw-portal-card"><header><b>IRONWOOD PUPPY PORTAL</b><small>SECURE FAMILY ACCESS</small></header><section><span><small>ASSIGNED PUPPY</small><b>Nova</b></span><span><small>UPDATES</small><b>5 published</b></span><span><small>DOCUMENTS</small><b>1 pending</b></span><span><small>JOURNEY</small><b>80% complete</b></span></section></div></section>
    <section className="iw-apply-section" id="apply"><div><span className="iw-kicker">APPLICATIONS · PLANNED PLACEMENTS</span><h2>Start with the right fit.</h2></div><Link href="/signup?website_template=ironwood-shepherds">Choose Ironwood style <ArrowRight size={15}/></Link></section>
    <footer className="iw-footer"><b>IRONWOOD GERMAN SHEPHERDS</b><span>Sample breeder identity · MyDogPortal Website Template 05</span><span>Powered by MyDogPortal</span></footer>
  </main>;
}
